/**
 * Cross-binding ownership guard for the first-run scaffold path.
 *
 * Incremental scaffolds are protected by the manifest: a file the user edited
 * is reported as a conflict and preserved. A *first* run has no manifest, so
 * that protection does not apply and every generated file is written
 * unconditionally — including files that belong to somebody else.
 *
 * This matters because bindings share paths. `AGENTS.md` at the project root is
 * generated by the codex, cursor, copilot-cli, kiro, and openclaw bindings
 * alike, and each keeps its own manifest. Scaffolding a second binding into a
 * project therefore looks like a first run to that binding and silently
 * replaces the first binding's file.
 *
 * The guard answers one question before anything is written: does a generated
 * path already hold different content, and if so, who put it there?
 *
 * @module
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

import type { GeneratedFile } from "../bindings/types.js";
import { readManifest } from "./manifest.js";

/** A generated path that already exists on disk holding different content. */
export interface OwnershipCollision {
  /** Relative path of the colliding file. */
  path: string;
  /**
   * Target whose manifest claims this path, or `null` when no manifest does —
   * meaning the file was hand-authored or produced by something else entirely.
   */
  owner: string | null;
}

/**
 * Find generated files that would overwrite content this target does not own.
 *
 * Byte-identical files are not collisions: rewriting them loses nothing.
 *
 * @param basePath - Absolute path to the project root
 * @param target - Binding target about to be scaffolded
 * @param generatedFiles - Files produced by the binding's scaffold function
 * @param knownTargets - All registered binding names, used to attribute owners
 * @returns Collisions in generation order; empty when writing is safe
 */
export function findUnownedCollisions(
  basePath: string,
  target: string,
  generatedFiles: GeneratedFile[],
  knownTargets: readonly string[],
): OwnershipCollision[] {
  const collisions: OwnershipCollision[] = [];

  // Other bindings' manifests, read at most once and only if something collides.
  let otherManifests: Array<{ target: string; files: Set<string> }> | null = null;
  function claimants(): Array<{ target: string; files: Set<string> }> {
    if (otherManifests) return otherManifests;
    otherManifests = [];
    for (const other of knownTargets) {
      if (other === target) continue;
      const manifest = readManifest(basePath, other);
      if (!manifest) continue;
      otherManifests.push({
        target: other,
        files: new Set(Object.keys(manifest.files)),
      });
    }
    return otherManifests;
  }

  for (const file of generatedFiles) {
    const absPath = join(basePath, file.path);
    if (!existsSync(absPath)) continue;

    let existing: string;
    try {
      existing = readFileSync(absPath, "utf-8");
    } catch {
      // Unreadable (directory, permissions, binary-ish): not our call to make.
      // Let the write itself fail loudly rather than guessing here.
      continue;
    }
    if (existing === file.content) continue;

    const owner = claimants().find((m) => m.files.has(file.path))?.target ?? null;
    collisions.push({ path: file.path, owner });
  }

  return collisions;
}

/**
 * Human-readable attribution for a collision, used in CLI output.
 */
export function describeOwner(collision: OwnershipCollision): string {
  return collision.owner
    ? `owned by the "${collision.owner}" scaffold`
    : "not generated by agentopology";
}
