/**
 * OpenAI Codex CLI binding.
 *
 * Generates `codex.toml`, `AGENTS.md`, `.codex/instructions.md`, and
 * supporting scripts from a parsed {@link TopologyAST}.
 *
 * Codex CLI uses TOML-based configuration and reads markdown instruction
 * files. Unlike Claude Code, Codex is a single-agent CLI — multi-agent
 * topologies are expressed as instruction sections in AGENTS.md rather
 * than separate agent directories.
 *
 * @module
 */

import type {
  TopologyAST,
  AgentNode,
  GateNode,
  HookDef,
  InterfaceDef,
  ScheduleJobDef,
  SkillDef,
  ToolBlockDef,
} from "../parser/ast.js";
import type { BindingTarget, GeneratedFile } from "./types.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Convert a kebab-case id to Title Case. */
function toTitle(id: string): string {
  return id
    .split(/[-_]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

/**
 * Map topology permission strings to Codex approval_policy values.
 *
 * Codex CLI supports three approval policies:
 *   - "suggest"    — shows diffs for approval (default, most restrictive)
 *   - "auto-edit"  — auto-applies file changes, asks for commands
 *   - "full-auto"  — auto-runs everything
 */
function mapApprovalPolicy(perm: string): string {
  // Codex-native values — pass through
  const nativeValues = ["suggest", "auto-edit", "full-auto"];
  if (nativeValues.includes(perm)) return perm;

  // Topology-level semantic values
  switch (perm) {
    case "supervised":
      return "suggest";
    case "autonomous":
      return "auto-edit";
    case "interactive":
      return "suggest";
    case "unrestricted":
      return "full-auto";
    // Claude Code native values mapped to Codex equivalents
    case "plan":
      return "suggest";
    case "auto":
      return "auto-edit";
    case "confirm":
      return "suggest";
    case "bypassPermissions":
      return "full-auto";
    default:
      return "suggest"; // safe default
  }
}

/**
 * Escape a TOML string value.
 * Wraps in double quotes, escaping internal quotes and backslashes.
 */
function tomlString(value: string): string {
  const escaped = value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n");
  return `"${escaped}"`;
}

/** Format a TOML array of strings on a single line. */
function tomlStringArray(values: string[]): string {
  return `[${values.map(tomlString).join(", ")}]`;
}

/** Generate a shell script stub with a header comment. */
function shellStub(description: string): string {
  return [
    "#!/usr/bin/env bash",
    `# ${description}`,
    "# Auto-generated by agentopology scaffold — edit as needed.",
    "set -euo pipefail",
    "",
    'echo "TODO: implement this script"',
    "",
  ].join("\n");
}

/** Generate an empty directory marker (a .gitkeep file). */
function gitkeep(dirPath: string): GeneratedFile {
  return { path: `${dirPath}/.gitkeep`, content: "" };
}

// ---------------------------------------------------------------------------
// TOML generation — codex.toml
// ---------------------------------------------------------------------------

/**
 * Generate the main `codex.toml` configuration file.
 *
 * Maps topology metadata, the most permissive agent's approval policy,
 * model, sandbox, and provider settings. Extension fields from
 * `extensions["codex"]` on the topology or agents are merged in.
 */
function generateCodexToml(ast: TopologyAST): GeneratedFile {
  const lines: string[] = [];

  lines.push("# Codex CLI configuration");
  lines.push("# Auto-generated by agentopology scaffold — edit as needed.");
  lines.push("");

  // Determine the primary model and approval policy from agents.
  // Use the first orchestrator or first agent's model, falling back to gpt-4o.
  const orchestrator = ast.nodes.find((n) => n.type === "orchestrator");
  const agents = ast.nodes.filter((n) => n.type === "agent") as AgentNode[];
  const primaryModel =
    (orchestrator as any)?.model ?? agents[0]?.model ?? "o4-mini";
  const primaryPermission = agents[0]?.permissions ?? "supervised";

  lines.push(`model = ${tomlString(primaryModel)}`);
  lines.push(`approval_policy = ${tomlString(mapApprovalPolicy(primaryPermission))}`);

  // Disable response storage if env has a flag or topology explicitly sets it
  const codexTopologyExt = getTopologyExtensions(ast);
  if (codexTopologyExt?.disable_response_storage != null) {
    lines.push(
      `disable_response_storage = ${codexTopologyExt.disable_response_storage === true}`
    );
  }

  lines.push("");

  // History settings from extensions
  if (codexTopologyExt?.history) {
    const history = codexTopologyExt.history as Record<string, unknown>;
    lines.push("[history]");
    if (history.max_conversations != null) {
      lines.push(`max_conversations = ${history.max_conversations}`);
    }
    if (history.persistence != null) {
      lines.push(`persistence = ${tomlString(String(history.persistence))}`);
    }
    lines.push("");
  }

  // Sandbox settings — first-class AST field, then extension, then derived
  const topSandbox = ast.settings?.sandbox;
  const sandboxType = topSandbox != null
    ? (typeof topSandbox === 'boolean' ? (topSandbox ? 'docker' : 'none') : String(topSandbox))
    : codexTopologyExt?.sandbox_type ?? deriveSandboxType(ast);
  if (sandboxType) {
    lines.push("[sandbox]");
    lines.push(`type = ${tomlString(String(sandboxType))}`);
    lines.push("");
  }

  // Providers from extensions or ast.providers
  const extProviders = codexTopologyExt?.providers as
    | Array<Record<string, unknown>>
    | undefined;
  if (extProviders && extProviders.length > 0) {
    // Extensions path takes priority
    for (const provider of extProviders) {
      lines.push("[[providers]]");
      if (provider.name) lines.push(`name = ${tomlString(String(provider.name))}`);
      if (provider.base_url)
        lines.push(`base_url = ${tomlString(String(provider.base_url))}`);
      if (provider.env_key)
        lines.push(`env_key = ${tomlString(String(provider.env_key))}`);
      lines.push("");
    }
  } else if (ast.providers && ast.providers.length > 0) {
    // Fallback: map ast.providers to Codex [[providers]] format
    for (const p of ast.providers) {
      lines.push("[[providers]]");
      lines.push(`name = ${tomlString(p.name)}`);
      if (p.baseUrl) lines.push(`base_url = ${tomlString(p.baseUrl)}`);
      if (p.apiKey) {
        // Convert ${ENV_VAR} to just ENV_VAR for Codex env_key format
        const envKey = p.apiKey.replace(/^\$\{(.+)\}$/, "$1");
        lines.push(`env_key = ${tomlString(envKey)}`);
      }
      lines.push("");
    }
  }

  // Fallback chain — document if present (Codex doesn't natively support it)
  const fallbackChain = ast.settings?.["fallback-chain"] as string[] | undefined;
  if (fallbackChain && fallbackChain.length > 0) {
    lines.push(`# Model fallback chain: ${fallbackChain.join(" -> ")}`);
    lines.push("");
  }

  // Merge any remaining extension fields as top-level TOML keys
  if (codexTopologyExt) {
    const handled = new Set([
      "disable_response_storage",
      "history",
      "sandbox_type",
      "providers",
    ]);
    for (const [key, value] of Object.entries(codexTopologyExt)) {
      if (handled.has(key)) continue;
      if (typeof value === "string") {
        lines.push(`${key} = ${tomlString(value)}`);
      } else if (typeof value === "boolean") {
        lines.push(`${key} = ${value}`);
      } else if (typeof value === "number") {
        lines.push(`${key} = ${value}`);
      }
    }
  }

  return {
    path: "codex.toml",
    content: lines.join("\n") + "\n",
  };
}

/**
 * Derive sandbox type from topology permissions.
 * More restrictive permissions suggest sandboxing.
 */
function deriveSandboxType(ast: TopologyAST): string | null {
  const agents = ast.nodes.filter((n) => n.type === "agent") as AgentNode[];
  const hasUnrestricted = agents.some(
    (a) =>
      a.permissions === "unrestricted" ||
      a.permissions === "full-auto" ||
      a.permissions === "bypassPermissions"
  );
  // If any agent is unrestricted, no sandbox (user opted out of restrictions)
  if (hasUnrestricted) return "none";
  // Default: no explicit sandbox section needed
  return null;
}

/**
 * Extract codex-specific extension fields from the topology level.
 * Checks settings.extensions["codex"] and any top-level extension block.
 */
function getTopologyExtensions(
  ast: TopologyAST
): Record<string, unknown> | null {
  const settingsExt = ast.settings?.extensions as
    | Record<string, Record<string, unknown>>
    | undefined;
  if (settingsExt?.codex) return settingsExt.codex;
  return null;
}

// ---------------------------------------------------------------------------
// AGENTS.md generation
// ---------------------------------------------------------------------------

/**
 * Generate `AGENTS.md` — the primary instructions file for Codex CLI.
 *
 * Since Codex is a single-agent CLI, multi-agent topologies are expressed
 * as instruction sections describing each agent's role, responsibilities,
 * tools, and memory access patterns. The orchestrator reads this file to
 * understand the full workflow.
 */
function generateAgentsMd(ast: TopologyAST): GeneratedFile {
  const sections: string[] = [];
  const name = ast.topology.name;

  // Header
  sections.push(`# ${toTitle(name)} — Agent Instructions`);
  sections.push("");
  if (ast.topology.description) {
    sections.push(ast.topology.description);
    sections.push("");
  }
  sections.push(`Version: ${ast.topology.version}`);
  if (ast.topology.patterns.length > 0) {
    sections.push(`Patterns: ${ast.topology.patterns.join(", ")}`);
  }
  sections.push("");

  // Orchestrator section
  const orch = ast.nodes.find((n) => n.type === "orchestrator");
  if (orch) {
    sections.push("## Orchestrator");
    sections.push("");
    sections.push(`Model: ${(orch as any).model}`);
    if ((orch as any).handles?.length > 0) {
      sections.push(`Handles: ${(orch as any).handles.join(", ")}`);
    }
    if ((orch as any).generates) {
      sections.push(`Generates: ${(orch as any).generates}`);
    }
    sections.push("");
  }

  // Flow section
  if (ast.edges.length > 0) {
    sections.push("## Flow");
    sections.push("");
    for (const edge of ast.edges) {
      let line = `${edge.from} -> ${edge.to}`;
      if (edge.condition) line += ` [when ${edge.condition}]`;
      if (edge.maxIterations) line += ` [max ${edge.maxIterations}]`;
      sections.push(`- ${line}`);
    }
    sections.push("");
  }

  // Schedules section (Codex doesn't natively support cron; document for reference)
  if (ast.schedules && ast.schedules.length > 0) {
    sections.push("## Schedules");
    sections.push("");
    for (const job of ast.schedules) {
      const timing = job.cron ? `runs at \`${job.cron}\`` : `runs ${job.every}`;
      const target = job.agent
        ? `triggers agent \`${job.agent}\``
        : job.action
          ? `triggers action \`${job.action}\``
          : "";
      const suffix = target ? `, ${target}` : "";
      const enabled = job.enabled === false ? " (disabled)" : "";
      sections.push(`- **${job.id}**: ${timing}${suffix}${enabled}`);
    }
    sections.push("");
  }

  // Interfaces section (document external interfaces for reference)
  if (ast.interfaces && ast.interfaces.length > 0) {
    sections.push("## Interfaces");
    sections.push("");
    for (const iface of ast.interfaces) {
      const details: string[] = [];
      if (iface.type) details.push(iface.type);
      for (const [k, v] of Object.entries(iface.config)) {
        details.push(`${k} ${v}`);
      }
      const desc = details.length > 0 ? details.join(", ") : "configured";
      sections.push(`- **${iface.id}**: ${desc}`);
    }
    sections.push("");
  }

  // Agent sections
  const agents = ast.nodes.filter((n) => n.type === "agent") as AgentNode[];
  if (agents.length > 0) {
    sections.push("## Agents");
    sections.push("");

    for (const agent of agents) {
      sections.push(`### ${toTitle(agent.id)}`);
      sections.push("");

      // Role
      const roleText =
        ast.roles[agent.role ?? ""] ?? ast.roles[agent.id] ?? agent.role;
      if (roleText) {
        sections.push(`**Role:** ${roleText}`);
        sections.push("");
      }

      // Description
      if (agent.description) {
        sections.push(agent.description);
        sections.push("");
      }

      // Model and permissions
      const model = agent.model ?? "o4-mini";
      const policy = mapApprovalPolicy(agent.permissions ?? "supervised");
      sections.push(`- **Model:** ${model}`);
      sections.push(`- **Approval policy:** ${policy}`);

      // Phase
      if (agent.phase != null) {
        sections.push(`- **Phase:** ${agent.phase}`);
      }

      // Prompt
      if (agent.prompt) {
        sections.push("");
        sections.push("#### Instructions");
        sections.push("");
        sections.push(agent.prompt);
        sections.push("");
      }

      // Tools
      if (agent.tools && agent.tools.length > 0) {
        sections.push(`- **Tools:** ${agent.tools.join(", ")}`);
      }
      if (agent.disallowedTools && agent.disallowedTools.length > 0) {
        sections.push(
          `- **Disallowed tools:** ${agent.disallowedTools.join(", ")}`
        );
      }

      // Skills
      if (agent.skills && agent.skills.length > 0) {
        sections.push(`- **Skills:** ${agent.skills.join(", ")}`);
      }

      // Memory access
      if (agent.reads && agent.reads.length > 0) {
        sections.push(`- **Reads:** ${agent.reads.join(", ")}`);
      }
      if (agent.writes && agent.writes.length > 0) {
        sections.push(`- **Writes:** ${agent.writes.join(", ")}`);
      }

      // Outputs
      if (agent.outputs) {
        sections.push("- **Outputs:**");
        for (const [field, values] of Object.entries(agent.outputs)) {
          sections.push(`  - ${field}: ${values.join(" | ")}`);
        }
      }

      // Behavior modifiers
      if (agent.behavior) {
        sections.push(`- **Behavior:** ${agent.behavior}`);
      }
      if (agent.skip) {
        sections.push(`- **Skip when:** ${agent.skip}`);
      }
      if (agent.isolation) {
        sections.push(`- **Isolation:** ${agent.isolation}`);
      }
      if (agent.background) {
        sections.push(`- **Background:** true`);
      }
      if (agent.retry != null) {
        sections.push(`- **Retry:** ${agent.retry}`);
      }
      if (agent.maxTurns != null) {
        sections.push(`- **Max turns:** ${agent.maxTurns}`);
      }

      // Scale
      if (agent.scale) {
        sections.push(
          `- **Scale:** ${agent.scale.mode} by ${agent.scale.by} (${agent.scale.min}-${agent.scale.max})`
        );
      }

      // Codex-specific extensions
      if (agent.extensions?.codex) {
        sections.push("- **Codex config:**");
        for (const [k, v] of Object.entries(agent.extensions.codex)) {
          sections.push(`  - ${k}: ${v}`);
        }
      }

      sections.push("");
    }
  }

  // Gates section
  const gates = ast.nodes.filter((n) => n.type === "gate") as GateNode[];
  if (gates.length > 0) {
    sections.push("## Gates");
    sections.push("");
    for (const gate of gates) {
      sections.push(`### ${toTitle(gate.id)}`);
      sections.push("");
      if (gate.after) sections.push(`- **After:** ${gate.after}`);
      if (gate.before) sections.push(`- **Before:** ${gate.before}`);
      if (gate.run) sections.push(`- **Run:** ${gate.run}`);
      if (gate.checks && gate.checks.length > 0) {
        sections.push(`- **Checks:** ${gate.checks.join(", ")}`);
      }
      if (gate.onFail) sections.push(`- **On fail:** ${gate.onFail}`);
      if (gate.retry != null) sections.push(`- **Retry:** ${gate.retry}`);
      sections.push(`- **Enforcement:** script-level — run gate script manually between agents`);
      sections.push("");
    }
  }

  // Triggers section
  if (ast.triggers.length > 0) {
    sections.push("## Triggers");
    sections.push("");
    for (const trigger of ast.triggers) {
      sections.push(`### ${trigger.name}`);
      sections.push(`Pattern: \`${trigger.pattern}\``);
      if (trigger.argument) sections.push(`Argument: ${trigger.argument}`);
      sections.push("");
    }
  }

  // Memory paths section
  if (Object.keys(ast.memory).length > 0) {
    sections.push("## Memory");
    sections.push("");
    if (ast.memory.domains) {
      sections.push(`- **Domains:** .codex/domains/`);
    }
    if (ast.memory.references) {
      sections.push(`- **References:** .codex/references/`);
    }
    if (ast.memory.metrics) {
      sections.push(`- **Metrics:** .codex/metrics.jsonl`);
    }
    if (ast.memory.workspace) {
      sections.push(`- **Workspace:** .codex/runs/`);
    }
    sections.push("");
  }

  return {
    path: "AGENTS.md",
    content: sections.join("\n") + "\n",
  };
}

// ---------------------------------------------------------------------------
// .codex/instructions.md
// ---------------------------------------------------------------------------

/**
 * Generate `.codex/instructions.md` — project-level instructions.
 *
 * This file contains topology-derived context: description, patterns,
 * skill summaries, and context includes.
 */
function generateInstructionsMd(ast: TopologyAST): GeneratedFile {
  const sections: string[] = [];

  sections.push(`# ${toTitle(ast.topology.name)}`);
  sections.push("");
  if (ast.topology.description) {
    sections.push(ast.topology.description);
    sections.push("");
  }
  sections.push(`Version: ${ast.topology.version}`);
  if (ast.topology.patterns.length > 0) {
    sections.push(`Patterns: ${ast.topology.patterns.join(", ")}`);
  }
  sections.push("");

  // Skills summary
  if (ast.skills.length > 0) {
    sections.push("## Skills");
    sections.push("");
    for (const skill of ast.skills) {
      sections.push(`### ${toTitle(skill.id)}`);
      if (skill.description) {
        sections.push(skill.description);
      }
      if (skill.scripts && skill.scripts.length > 0) {
        sections.push(`Scripts: ${skill.scripts.join(", ")}`);
      }
      sections.push("");
    }
  }

  // Context includes
  if (ast.context.includes && ast.context.includes.length > 0) {
    sections.push("## References");
    sections.push("");
    for (const inc of ast.context.includes) {
      sections.push(`- ${inc}`);
    }
    sections.push("");
  }

  // Environment variables
  if (Object.keys(ast.env).length > 0) {
    sections.push("## Environment");
    sections.push("");
    for (const [key, value] of Object.entries(ast.env)) {
      sections.push(`- \`${key}\`: ${value}`);
    }
    sections.push("");
  }

  return {
    path: ".codex/instructions.md",
    content: sections.join("\n") + "\n",
  };
}

// ---------------------------------------------------------------------------
// Memory directories
// ---------------------------------------------------------------------------

/** Generate memory structure directories under .codex/. */
function generateMemory(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  if (ast.memory.domains) {
    files.push(gitkeep(".codex/domains"));
  }
  if (ast.memory.references) {
    files.push(gitkeep(".codex/references"));
  }
  if (ast.memory.metrics) {
    files.push({
      path: ".codex/metrics.jsonl",
      content: "",
    });
  }
  if (ast.memory.workspace) {
    files.push(gitkeep(".codex/runs"));
  }

  return files;
}

// ---------------------------------------------------------------------------
// Gate scripts
// ---------------------------------------------------------------------------

/** Generate gate script stubs under .codex/scripts/. */
function generateGateScripts(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  for (const node of ast.nodes) {
    if (node.type !== "gate") continue;
    const gate = node as GateNode;
    if (gate.run) {
      const scriptName = gate.run.replace(/^.*\//, "").replace(/\s.*$/, "");
      files.push({
        path: `.codex/scripts/${scriptName}`,
        content: shellStub(`Gate: ${gate.id} — ${gate.run}`),
      });
    }
  }

  return files;
}

// ---------------------------------------------------------------------------
// Hook scripts
// ---------------------------------------------------------------------------

/** Generate hook script stubs under .codex/scripts/. */
function generateHookScripts(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  for (const hook of ast.hooks) {
    if (!hook.run) continue;
    const scriptName = hook.run.replace(/^.*\//, "").replace(/\s.*$/, "");
    files.push({
      path: `.codex/scripts/${scriptName}`,
      content: [
        "#!/usr/bin/env bash",
        `# Hook: ${hook.name} — fires on ${hook.on}`,
        "# Auto-generated by agentopology scaffold — edit as needed.",
        "set -euo pipefail",
        "",
        `echo "TODO: implement ${hook.name} hook"`,
        "",
      ].join("\n"),
    });
  }

  return files;
}

// ---------------------------------------------------------------------------
// Tool scripts
// ---------------------------------------------------------------------------

/** Generate tool script stubs under .codex/scripts/. */
function generateToolScripts(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  for (const tool of ast.toolDefs) {
    const ext =
      tool.lang === "python" ? "py" : tool.lang === "node" ? "js" : "sh";
    const shebang =
      tool.lang === "python"
        ? "#!/usr/bin/env python3"
        : tool.lang === "node"
          ? "#!/usr/bin/env node"
          : "#!/usr/bin/env bash";

    const lines = [
      shebang,
      `# Tool: ${tool.id} — ${tool.description}`,
      "# Auto-generated by agentopology scaffold — edit as needed.",
      "",
    ];

    if (tool.lang === "bash" || !tool.lang) {
      lines.push("set -euo pipefail");
      lines.push("");
    }

    if (tool.args && tool.args.length > 0) {
      lines.push(`# Args: ${tool.args.join(", ")}`);
      lines.push("");
    }

    lines.push(`echo "TODO: implement ${tool.id}"`);
    lines.push("");

    files.push({
      path: `.codex/scripts/${tool.id}.${ext}`,
      content: lines.join("\n"),
    });
  }

  return files;
}

// ---------------------------------------------------------------------------
// Metering script
// ---------------------------------------------------------------------------

/** Generate metering script stub. */
function generateMetering(ast: TopologyAST): GeneratedFile | null {
  if (!ast.metering) return null;

  const m = ast.metering;
  const lines = [
    "#!/usr/bin/env bash",
    "# Metering / cost tracking script",
    "# Auto-generated by agentopology scaffold — edit as needed.",
    "set -euo pipefail",
    "",
    `# Track: ${m.track.join(", ")}`,
    `# Per: ${m.per.join(", ")}`,
    `# Output: ${m.output} (${m.format})`,
    `# Pricing: ${m.pricing}`,
    "",
    'echo "TODO: implement metrics collection"',
    "",
  ];

  return {
    path: "scripts/collect-metrics.sh",
    content: lines.join("\n"),
  };
}

// ---------------------------------------------------------------------------
// Workspace protocol
// ---------------------------------------------------------------------------

/** Generate workspace-protocol.md if workspace memory has a protocol field. */
function generateWorkspaceProtocol(ast: TopologyAST): GeneratedFile | null {
  const workspace = ast.memory.workspace as Record<string, unknown> | undefined;
  if (!workspace || !workspace.protocol) return null;

  const protocol = workspace.protocol as string;
  const sections: string[] = [];
  sections.push("# Workspace Protocol");
  sections.push("");

  // Directory structure from workspace.structure
  const structure = workspace.structure;
  if (structure && Array.isArray(structure)) {
    sections.push("## Directory Structure");
    for (const item of structure) {
      sections.push(`- ${item}`);
    }
    sections.push("");
  }

  // Read/Write rules from agent nodes
  const agents = ast.nodes.filter((n) => n.type === "agent") as AgentNode[];
  if (agents.length > 0) {
    sections.push("## Read/Write Rules");
    for (const agent of agents) {
      const reads = agent.reads ?? [];
      const writes = agent.writes ?? [];
      if (reads.length > 0 || writes.length > 0) {
        sections.push(`### ${toTitle(agent.id)}`);
        if (reads.length > 0) {
          sections.push(`- Reads: ${reads.join(", ")}`);
        }
        if (writes.length > 0) {
          sections.push(`- Writes: ${writes.join(", ")}`);
        }
        sections.push("");
      }
    }
  }

  return {
    path: `.codex/${protocol}`,
    content: sections.join("\n") + "\n",
  };
}

// ---------------------------------------------------------------------------
// Skill documentation
// ---------------------------------------------------------------------------

/** Generate skill documentation files under .codex/skills/. */
function generateSkills(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  for (const skill of ast.skills) {
    const sections: string[] = [];

    sections.push(`# ${toTitle(skill.id)} Skill`);
    sections.push("");
    if (skill.description) {
      sections.push(skill.description);
      sections.push("");
    }
    if (skill.scripts && skill.scripts.length > 0) {
      sections.push("## Scripts");
      for (const s of skill.scripts) {
        sections.push(`- ${s}`);
      }
      sections.push("");
    }
    if (skill.domains && skill.domains.length > 0) {
      sections.push("## Domains");
      for (const d of skill.domains) {
        sections.push(`- ${d}`);
      }
      sections.push("");
    }
    if (skill.references && skill.references.length > 0) {
      sections.push("## References");
      for (const r of skill.references) {
        sections.push(`- ${r}`);
      }
      sections.push("");
    }

    files.push({
      path: `.codex/skills/${skill.id}.md`,
      content: sections.join("\n") + "\n",
    });
  }

  return files;
}

// ---------------------------------------------------------------------------
// Binding export
// ---------------------------------------------------------------------------

/** OpenAI Codex CLI binding — full implementation. */
export const codexBinding: BindingTarget = {
  name: "codex",
  description:
    "OpenAI Codex CLI — generates codex.toml, AGENTS.md, .codex/ directory structure, and scripts.",

  scaffold(ast: TopologyAST): GeneratedFile[] {
    const files: GeneratedFile[] = [];

    // 1. codex.toml — main configuration
    files.push(generateCodexToml(ast));

    // 2. AGENTS.md — agent instructions with roles, flow, memory paths
    files.push(generateAgentsMd(ast));

    // 3. .codex/instructions.md — project-level instructions
    files.push(generateInstructionsMd(ast));

    // 4. Memory directories
    files.push(...generateMemory(ast));

    // 5. Skill documentation
    files.push(...generateSkills(ast));

    // 6. Gate scripts
    files.push(...generateGateScripts(ast));

    // 7. Hook scripts
    files.push(...generateHookScripts(ast));

    // 8. Tool scripts
    files.push(...generateToolScripts(ast));

    // 9. Workspace protocol
    const wsProtocol = generateWorkspaceProtocol(ast);
    if (wsProtocol) files.push(wsProtocol);

    // 10. Metering
    const meteringFile = generateMetering(ast);
    if (meteringFile) files.push(meteringFile);

    return files;
  },
};
