/**
 * Google Gemini CLI binding.
 *
 * Generates the `.gemini/` directory structure and supporting files from a
 * parsed {@link TopologyAST}.
 *
 * Gemini CLI structure:
 *   .gemini/CONTEXT.md            — Main instructions (never root GEMINI.md)
 *   .gemini/settings.json         — Tool permissions, model config, sandbox
 *   .gemini/instructions.md       — Detailed project instructions
 *   .gemini/commands/<name>.md    — Custom command files from triggers
 *
 * @module
 */

import type {
  TopologyAST,
  AgentNode,
  GateNode,
  GroupNode,
  HumanNode,
  HookDef,
  SkillDef,
  ToolBlockDef,
  SchemaFieldDef,
  SchemaType,
  RetryConfig,
  CircuitBreakerConfig,
  PromptVariant,
} from "../parser/ast.js";
import { deduplicateFiles } from "./types.js";
import type { BindingTarget, GeneratedFile } from "./types.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Convert a kebab-case id to Title Case. */
function toTitle(id: string): string {
  return id
    .split(/[-_]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

/** Generate a shell script stub with a header comment. */
function shellStub(description: string): string {
  return [
    "#!/usr/bin/env bash",
    `# ${description}`,
    "# Auto-generated by agentopology scaffold — edit as needed.",
    'set -euo pipefail',
    "",
    'echo "TODO: implement this script"',
    "",
  ].join("\n");
}

/** Generate an empty directory marker (a .gitkeep file). */
function gitkeep(dirPath: string): GeneratedFile {
  return { path: `${dirPath}/.gitkeep`, content: "", category: "machine" };
}

/**
 * Map topology permission strings to Gemini CLI approval settings.
 *
 * Gemini CLI permission model:
 *   supervised  -> default (asks for approval)
 *   autonomous  -> yolo (auto-approve all tools)
 *   interactive -> default (asks for approval)
 *   unrestricted -> sandbox off + yolo
 *
 * Returns a partial settings object to merge.
 */
function mapPermissions(perm: string): { sandbox?: boolean; toolApproval?: string } {
  switch (perm) {
    case "supervised":
      return { toolApproval: "default" };
    case "autonomous":
      return { toolApproval: "yolo" };
    case "interactive":
      return { toolApproval: "default" };
    case "unrestricted":
      return { sandbox: false, toolApproval: "yolo" };
    default:
      return {};
  }
}

/** Format a SchemaType to a human-readable string. */
function formatSchemaType(t: SchemaType): string {
  switch (t.kind) {
    case "primitive":
      return t.value;
    case "array":
      return `${formatSchemaType(t.itemType)}[]`;
    case "enum":
      return t.values.join(" | ");
    case "ref":
      return t.name;
  }
}

/** Format a SchemaFieldDef to a readable line. */
function formatSchemaField(f: SchemaFieldDef): string {
  const opt = f.optional ? "?" : "";
  return `- ${f.name}${opt}: ${formatSchemaType(f.type)}`;
}

// ---------------------------------------------------------------------------
// Section generators
// ---------------------------------------------------------------------------

/**
 * Generate the main GEMINI.md file.
 *
 * This is the primary instructions file that Gemini CLI reads. It contains
 * the topology description, agent roles, flow, and orchestration instructions.
 */
function generateGeminiMd(ast: TopologyAST): GeneratedFile {
  const sections: string[] = [];

  // Header
  sections.push(`# ${toTitle(ast.topology.name)}`);
  sections.push("");
  if (ast.topology.description) {
    sections.push(ast.topology.description);
    sections.push("");
  }
  sections.push(`Version: ${ast.topology.version}`);
  if (ast.topology.patterns.length > 0) {
    sections.push(`Patterns: ${ast.topology.patterns.join(", ")}`);
  }
  sections.push("");

  // Orchestrator section
  const orch = ast.nodes.find((n) => n.type === "orchestrator");
  if (orch) {
    sections.push("## Orchestrator");
    sections.push("");
    sections.push(`Model: ${(orch as any).model}`);
    if ((orch as any).handles?.length > 0) {
      sections.push(`Handles: ${(orch as any).handles.join(", ")}`);
    }
    if ((orch as any).generates) {
      sections.push(`Generates: ${(orch as any).generates}`);
    }
    sections.push("");
  }

  // Agent sections
  const agents = ast.nodes.filter((n) => n.type === "agent") as AgentNode[];
  if (agents.length > 0) {
    sections.push("## Agents");
    sections.push("");
    for (const agent of agents) {
      sections.push(`### ${toTitle(agent.id)}`);
      sections.push("");

      const roleText = ast.roles[agent.role ?? ""] ?? ast.roles[agent.id] ?? agent.role;
      if (agent.description) {
        sections.push(agent.description);
        sections.push("");
      } else if (roleText) {
        sections.push(roleText);
        sections.push("");
      }

      if (agent.prompt) {
        sections.push(agent.prompt);
        sections.push("");
      }

      if (agent.model) sections.push(`- Model: ${agent.model}`);
      if (agent.phase != null) sections.push(`- Phase: ${agent.phase}`);
      if (agent.tools && agent.tools.length > 0) {
        sections.push(`- Tools: ${agent.tools.join(", ")}`);
      }
      if (agent.disallowedTools && agent.disallowedTools.length > 0) {
        sections.push(`- Disallowed tools: ${agent.disallowedTools.join(", ")}`);
      }
      if (agent.skills && agent.skills.length > 0) {
        sections.push(`- Skills: ${agent.skills.join(", ")}`);
      }
      if (agent.reads && agent.reads.length > 0) {
        sections.push(`- Reads: ${agent.reads.join(", ")}`);
      }
      if (agent.writes && agent.writes.length > 0) {
        sections.push(`- Writes: ${agent.writes.join(", ")}`);
      }
      if (agent.behavior) sections.push(`- Behavior: ${agent.behavior}`);
      if (agent.skip) sections.push(`- Skip when: ${agent.skip}`);

      // Outputs
      if (agent.outputs) {
        sections.push("- Outputs:");
        for (const [field, values] of Object.entries(agent.outputs)) {
          sections.push(`  - ${field}: ${values.join(" | ")}`);
        }
      }

      // Timeout
      if (agent.timeout) {
        sections.push(`- Maximum execution time: ${agent.timeout}`);
      }

      // On-fail
      if (agent.onFail) {
        sections.push(`- On failure: ${agent.onFail}`);
      }

      // Retry
      if (agent.retry != null) {
        if (typeof agent.retry === "number") {
          sections.push(`- Retry: up to ${agent.retry} times on failure`);
        } else {
          const r = agent.retry as RetryConfig;
          const parts = [`max ${r.max} attempts`];
          if (r.backoff) parts.push(`${r.backoff} backoff`);
          if (r.interval) parts.push(`interval ${r.interval}`);
          if (r.maxInterval) parts.push(`max interval ${r.maxInterval}`);
          if (r.jitter) parts.push(`with jitter`);
          if (r.nonRetryable && r.nonRetryable.length > 0) {
            parts.push(`non-retryable: ${r.nonRetryable.join(", ")}`);
          }
          sections.push(`- Retry strategy: ${parts.join(", ")}`);
        }
      }

      // Output format
      if (agent.outputFormat) {
        sections.push(`- Output format: ${agent.outputFormat}`);
      }

      // Log level
      if (agent.logLevel) {
        sections.push(`- Log verbosity: ${agent.logLevel}`);
      }

      // Join semantics
      if (agent.join) {
        sections.push(`- Wait for: ${agent.join} (upstream join strategy)`);
      }

      // Circuit breaker
      if (agent.circuitBreaker) {
        const cb = agent.circuitBreaker;
        sections.push(`- Circuit breaker: threshold=${cb.threshold}, window=${cb.window}, cooldown=${cb.cooldown}`);
      }

      // Compensates
      if (agent.compensates) {
        sections.push(`- Compensates: ${agent.compensates} (can undo its side effects)`);
      }

      // Input/Output schemas
      if (agent.inputSchema && agent.inputSchema.length > 0) {
        sections.push("- Input schema:");
        for (const field of agent.inputSchema) {
          sections.push(`  ${formatSchemaField(field)}`);
        }
      }
      if (agent.outputSchema && agent.outputSchema.length > 0) {
        sections.push("- Output schema:");
        for (const field of agent.outputSchema) {
          sections.push(`  ${formatSchemaField(field)}`);
        }
      }

      // Rate limit
      if (agent.rateLimit) {
        sections.push(`- Rate limit: ${agent.rateLimit}`);
      }

      // Artifacts: produces/consumes
      if (agent.produces && agent.produces.length > 0) {
        sections.push(`- Produces: ${agent.produces.join(", ")}`);
      }
      if (agent.consumes && agent.consumes.length > 0) {
        sections.push(`- Consumes: ${agent.consumes.join(", ")}`);
      }

      // Variants
      if (agent.variants && agent.variants.length > 0) {
        sections.push("- Variants:");
        for (const v of agent.variants) {
          const parts = [`${v.id} (weight: ${v.weight})`];
          if (v.model) parts.push(`model: ${v.model}`);
          if (v.temperature != null) parts.push(`temperature: ${v.temperature}`);
          sections.push(`  - ${parts.join(", ")}`);
        }
      }

      sections.push("");
    }
  }

  // Human nodes
  const humans = ast.nodes.filter((n) => n.type === "human") as HumanNode[];
  if (humans.length > 0) {
    sections.push("## Human Checkpoints");
    sections.push("");
    for (const human of humans) {
      sections.push(`### ${toTitle(human.id)}`);
      sections.push("");
      if (human.description) {
        sections.push(human.description);
        sections.push("");
      }
      sections.push("**This is a human pause point.** Execution stops here until a human provides input or approval.");
      if (human.timeout) sections.push(`- Timeout: ${human.timeout}`);
      if (human.onTimeout) sections.push(`- On timeout: ${human.onTimeout}`);
      sections.push("");
    }
  }

  // Group nodes
  const groups = ast.nodes.filter((n) => n.type === "group") as GroupNode[];
  if (groups.length > 0) {
    sections.push("## Group Chats");
    sections.push("");
    for (const group of groups) {
      sections.push(`### ${toTitle(group.id)}`);
      sections.push("");
      if (group.description) {
        sections.push(group.description);
        sections.push("");
      }
      sections.push(`- Members: ${group.members.join(", ")}`);
      if (group.speakerSelection) sections.push(`- Speaker selection: ${group.speakerSelection}`);
      if (group.maxRounds != null) sections.push(`- Max rounds: ${group.maxRounds}`);
      if (group.termination) sections.push(`- Termination: ${group.termination}`);
      if (group.timeout) sections.push(`- Timeout: ${group.timeout}`);
      sections.push("");
    }
  }

  // Flow section
  if (ast.edges.length > 0) {
    sections.push("## Flow");
    sections.push("");
    for (const edge of ast.edges) {
      const arrow = edge.isError ? `-x->` : `->`;
      let line = `${edge.from} ${arrow} ${edge.to}`;
      if (edge.errorType) line += ` [error: ${edge.errorType}]`;
      if (edge.condition) line += ` [when ${edge.condition}]`;
      if (edge.maxIterations) line += ` [max ${edge.maxIterations}]`;
      if (edge.weight != null) line += ` [weight ${edge.weight}]`;
      if (edge.race) line += ` [race]`;
      if (edge.tolerance != null) line += ` [tolerance: ${edge.tolerance}]`;
      if (edge.wait) line += ` [wait ${edge.wait}]`;
      if (edge.reflection) line += ` [reflection]`;
      sections.push(`- ${line}`);
    }
    sections.push("");
  }

  // Gates section
  const gates = ast.nodes.filter((n) => n.type === "gate") as GateNode[];
  if (gates.length > 0) {
    sections.push("## Gates");
    sections.push("");
    for (const gate of gates) {
      sections.push(`### ${toTitle(gate.id)}`);
      if (gate.after) sections.push(`- After: ${gate.after}`);
      if (gate.before) sections.push(`- Before: ${gate.before}`);
      if (gate.run) sections.push(`- Run: ${gate.run}`);
      if (gate.checks && gate.checks.length > 0) {
        sections.push(`- Checks: ${gate.checks.join(", ")}`);
      }
      if (gate.onFail) sections.push(`- On fail: ${gate.onFail}`);
      sections.push(`- Enforcement: script-level — run gate script manually between agents`);
      sections.push("");
    }
  }

  // Triggers section
  if (ast.triggers.length > 0) {
    sections.push("## Commands");
    sections.push("");
    for (const trigger of ast.triggers) {
      sections.push(`- \`/${trigger.name}\`: ${trigger.pattern}`);
    }
    sections.push("");
  }

  // Include references
  if (ast.context.includes && ast.context.includes.length > 0) {
    sections.push("## References");
    sections.push("");
    for (const inc of ast.context.includes) {
      sections.push(`- ${inc}`);
    }
    sections.push("");
  }

  const DEFAULT_PATH = ".gemini/CONTEXT.md";
  let contextPath = ast.context.file ?? DEFAULT_PATH;

  // Safety: never overwrite the user's root-level GEMINI.md
  if (contextPath === "GEMINI.md" || contextPath === "./GEMINI.md") {
    contextPath = DEFAULT_PATH;
  }

  return {
    path: contextPath,
    content: sections.join("\n") + "\n",
    category: "agent",
  };
}

/**
 * Generate .gemini/settings.json.
 *
 * Maps topology permissions, tool allow/deny lists, model config,
 * sandbox mode, and MCP server configuration.
 */
function generateSettings(ast: TopologyAST): GeneratedFile {
  const settings: Record<string, unknown> = {};

  // Determine the most restrictive global permission from agents
  // Use the topology-level settings permission if available
  let globalPermission: string | undefined;
  const agents = ast.nodes.filter((n) => n.type === "agent") as AgentNode[];
  for (const agent of agents) {
    if (agent.permissions) {
      // Use the first agent's permissions as a baseline,
      // but 'supervised' takes priority (most restrictive)
      if (!globalPermission || agent.permissions === "supervised") {
        globalPermission = agent.permissions;
      }
    }
  }

  if (globalPermission) {
    const mapped = mapPermissions(globalPermission);
    if (mapped.toolApproval) settings.toolApproval = mapped.toolApproval;
    if (mapped.sandbox !== undefined) settings.sandbox = mapped.sandbox;
  }

  // First-class sandbox field from settings takes precedence
  const settingsSandbox = ast.settings?.sandbox;
  if (settingsSandbox !== undefined && settingsSandbox !== null) {
    if (typeof settingsSandbox === "boolean") {
      settings.sandbox = settingsSandbox;
    } else if (settingsSandbox === "true" || settingsSandbox === "false") {
      settings.sandbox = settingsSandbox === "true";
    } else {
      // String values like "docker", "none", "network-only" — pass through
      settings.sandbox = settingsSandbox;
    }
  }

  // Tool allow/deny lists from settings block
  const perms = ast.settings;
  if (perms) {
    const allow = perms.allow as string[] | undefined;
    const deny = perms.deny as string[] | undefined;

    if (allow && allow.length > 0) {
      settings.allowedTools = allow;
    }
    if (deny && deny.length > 0) {
      settings.deniedTools = deny;
    }
  }

  // Environment variables
  const envVars: Record<string, string> = {};
  for (const [key, val] of Object.entries(ast.env)) {
    envVars[key] = typeof val === "string" ? val : val.value;
  }

  // If a google provider exists, scaffold the GEMINI_API_KEY env var
  if (ast.providers && ast.providers.length > 0) {
    const googleProvider = ast.providers.find((p) => p.name === "google");
    if (googleProvider?.apiKey) {
      const envVarMatch = googleProvider.apiKey.match(/^\$\{(.+)\}$/);
      if (envVarMatch) {
        envVars[envVarMatch[1]] = googleProvider.apiKey;
      }
    }
  }

  if (Object.keys(envVars).length > 0) {
    settings.env = envVars;
  }

  // Model configuration from defaults or first agent
  const defaults = ast.defaults;
  const firstAgent = agents[0];

  const modelConfig: Record<string, unknown> = {};
  const temp = defaults?.temperature ?? firstAgent?.temperature;
  if (temp != null) modelConfig.temperature = temp;
  const maxTok = defaults?.maxTokens ?? firstAgent?.maxTokens;
  if (maxTok != null) modelConfig.maxOutputTokens = maxTok;
  const tp = defaults?.topP ?? firstAgent?.topP;
  if (tp != null) modelConfig.topP = tp;
  const tk = defaults?.topK ?? firstAgent?.topK;
  if (tk != null) modelConfig.topK = tk;

  if (Object.keys(modelConfig).length > 0) {
    settings.modelConfig = modelConfig;
  }

  // Thinking / reasoning config
  const thinkingLevel = defaults?.thinking ?? firstAgent?.thinking;
  if (thinkingLevel && thinkingLevel !== "off") {
    const thinkingConfig: Record<string, unknown> = { thinkingMode: thinkingLevel };
    const thinkingBudget = firstAgent?.thinkingBudget;
    if (thinkingBudget != null) thinkingConfig.thinkingBudget = thinkingBudget;
    settings.thinkingConfig = thinkingConfig;
  }

  // Merge gemini-cli extension fields from topology-level settings
  // (handled at the end to allow overrides)

  return {
    path: ".gemini/settings.json",
    content: JSON.stringify(settings, null, 2) + "\n",
    category: "machine",
  };
}

/**
 * Generate .gemini/instructions.md with detailed project instructions.
 *
 * Contains agent definitions, role descriptions, skill details, memory
 * configuration, and workspace protocol information.
 */
function generateInstructions(ast: TopologyAST): GeneratedFile {
  const sections: string[] = [];
  const name = ast.topology.name;

  sections.push(`# ${toTitle(name)} — Project Instructions`);
  sections.push("");
  if (ast.topology.description) {
    sections.push(ast.topology.description);
    sections.push("");
  }

  // Roles
  if (Object.keys(ast.roles).length > 0) {
    sections.push("## Roles");
    sections.push("");
    for (const [role, desc] of Object.entries(ast.roles)) {
      sections.push(`### ${toTitle(role)}`);
      sections.push(desc);
      sections.push("");
    }
  }

  // Skills
  if (ast.skills.length > 0) {
    sections.push("## Skills");
    sections.push("");
    for (const skill of ast.skills) {
      sections.push(`### ${toTitle(skill.id)}`);
      if (skill.description) sections.push(skill.description);
      if (skill.scripts && skill.scripts.length > 0) {
        sections.push(`Scripts: ${skill.scripts.join(", ")}`);
      }
      if (skill.domains && skill.domains.length > 0) {
        sections.push(`Domains: ${skill.domains.join(", ")}`);
      }
      if (skill.references && skill.references.length > 0) {
        sections.push(`References: ${skill.references.join(", ")}`);
      }
      sections.push("");
    }
  }

  // Memory configuration
  const memory = ast.memory;
  if (Object.keys(memory).length > 0) {
    sections.push("## Memory");
    sections.push("");
    if (memory.domains) sections.push("- Domains: configured");
    if (memory.references) sections.push("- References: configured");
    if (memory.metrics) sections.push("- Metrics: configured");
    if (memory.workspace) sections.push("- Workspace: configured");
    sections.push("");
  }

  // Workspace protocol
  const workspace = memory.workspace as Record<string, unknown> | undefined;
  if (workspace?.protocol) {
    sections.push("## Workspace Protocol");
    sections.push("");
    const structure = workspace.structure;
    if (structure && Array.isArray(structure)) {
      sections.push("### Directory Structure");
      for (const item of structure) {
        sections.push(`- ${item}`);
      }
      sections.push("");
    }

    // Read/write rules from agents
    const agents = ast.nodes.filter((n) => n.type === "agent") as AgentNode[];
    const rwAgents = agents.filter(
      (a) => (a.reads && a.reads.length > 0) || (a.writes && a.writes.length > 0)
    );
    if (rwAgents.length > 0) {
      sections.push("### Read/Write Rules");
      for (const agent of rwAgents) {
        sections.push(`#### ${toTitle(agent.id)}`);
        if (agent.reads && agent.reads.length > 0) {
          sections.push(`- Reads: ${agent.reads.join(", ")}`);
        }
        if (agent.writes && agent.writes.length > 0) {
          sections.push(`- Writes: ${agent.writes.join(", ")}`);
        }
        sections.push("");
      }
    }
  }

  // Depth configuration
  if (ast.depth.levels.length > 0) {
    sections.push("## Depth Levels");
    sections.push("");
    if (ast.depth.factors.length > 0) {
      sections.push(`Factors: ${ast.depth.factors.join(", ")}`);
      sections.push("");
    }
    for (const level of ast.depth.levels) {
      let line = `- Level ${level.level}: ${level.label}`;
      if (level.omit.length > 0) {
        line += ` (omit: ${level.omit.join(", ")})`;
      }
      sections.push(line);
    }
    sections.push("");
  }

  // Tool definitions
  if (ast.toolDefs.length > 0) {
    sections.push("## Tools");
    sections.push("");
    for (const tool of ast.toolDefs) {
      sections.push(`### ${tool.id}`);
      sections.push(tool.description);
      sections.push(`Script: ${tool.script} (${tool.lang ?? "bash"})`);
      if (tool.args && tool.args.length > 0) {
        sections.push(`Args: ${tool.args.join(", ")}`);
      }
      sections.push("");
    }
  }

  // Schedules section
  if (ast.schedules.length > 0) {
    sections.push("## Schedules");
    sections.push("");
    for (const job of ast.schedules) {
      const expr = job.cron ? `cron: ${job.cron}` : job.every ? `every: ${job.every}` : "";
      const target = job.agent ? `agent: ${job.agent}` : job.action ? `action: ${job.action}` : "";
      sections.push(`- **${job.id}**: ${expr}${target ? ` -> ${target}` : ""}${job.enabled === false ? " (disabled)" : ""}`);
    }
    sections.push("");
  }

  // Interfaces section
  if (ast.interfaces.length > 0) {
    sections.push("## Interfaces");
    sections.push("");
    for (const iface of ast.interfaces) {
      const typePart = iface.type ? ` (${iface.type})` : "";
      const configKeys = Object.keys(iface.config);
      const configPart = configKeys.length > 0 ? ` — ${configKeys.map((k) => `${k}: ${iface.config[k]}`).join(", ")}` : "";
      sections.push(`- **${iface.id}**${typePart}${configPart}`);
    }
    sections.push("");
  }

  // Fallback chain from settings
  const fallbackChain = ast.settings?.["fallback-chain"];
  if (fallbackChain) {
    sections.push("## Fallback Chain");
    sections.push("");
    if (Array.isArray(fallbackChain)) {
      sections.push(`Models: ${(fallbackChain as string[]).join(" -> ")}`);
    } else {
      sections.push(`Fallback chain: ${fallbackChain}`);
    }
    sections.push("");
  }

  // Metering
  if (ast.metering) {
    const m = ast.metering;
    sections.push("## Metering");
    sections.push("");
    sections.push(`- Track: ${m.track.join(", ")}`);
    sections.push(`- Per: ${m.per.join(", ")}`);
    sections.push(`- Output: ${m.output} (${m.format})`);
    sections.push(`- Pricing: ${m.pricing}`);
    sections.push("");
  }

  // Defaults
  if (ast.defaults) {
    const d = ast.defaults;
    sections.push("## Defaults");
    sections.push("");
    if (d.temperature != null) sections.push(`- Temperature: ${d.temperature}`);
    if (d.maxTokens != null) sections.push(`- Max tokens: ${d.maxTokens}`);
    if (d.topP != null) sections.push(`- Top-p: ${d.topP}`);
    if (d.topK != null) sections.push(`- Top-k: ${d.topK}`);
    if (d.stop) sections.push(`- Stop sequences: ${d.stop.join(", ")}`);
    if (d.seed != null) sections.push(`- Seed: ${d.seed}`);
    if (d.thinking) sections.push(`- Thinking: ${d.thinking}`);
    if (d.thinkingBudget != null) sections.push(`- Thinking budget: ${d.thinkingBudget} tokens`);
    if (d.outputFormat) sections.push(`- Output format: ${d.outputFormat}`);
    if (d.timeout) sections.push(`- Timeout: ${d.timeout}`);
    if (d.logLevel) sections.push(`- Log level: ${d.logLevel}`);
    sections.push("");
  }

  // Observability
  if (ast.observability) {
    const o = ast.observability;
    sections.push("## Observability");
    sections.push("");
    sections.push(`- Enabled: ${o.enabled}`);
    sections.push(`- Level: ${o.level}`);
    sections.push(`- Exporter: ${o.exporter}`);
    if (o.endpoint) sections.push(`- Endpoint: ${o.endpoint}`);
    if (o.service) sections.push(`- Service: ${o.service}`);
    sections.push(`- Sample rate: ${o.sampleRate}`);
    sections.push(`- Capture: prompts=${o.capture.prompts}, completions=${o.capture.completions}, toolArgs=${o.capture.toolArgs}, toolResults=${o.capture.toolResults}`);
    sections.push(`- Spans: agents=${o.spans.agents}, tools=${o.spans.tools}, gates=${o.spans.gates}, memory=${o.spans.memory}`);
    sections.push("");
  }

  // Checkpoint
  if (ast.checkpoint) {
    const c = ast.checkpoint;
    sections.push("## Checkpoint");
    sections.push("");
    sections.push(`- Backend: ${c.backend}`);
    if (c.connection) sections.push(`- Connection: ${c.connection}`);
    sections.push(`- Strategy: ${c.strategy}`);
    if (c.ttl) sections.push(`- TTL: ${c.ttl}`);
    if (c.replay) {
      sections.push(`- Replay: enabled=${c.replay.enabled}`);
      if (c.replay.maxHistory != null) sections.push(`  - Max history: ${c.replay.maxHistory}`);
      if (c.replay.branch != null) sections.push(`  - Branch: ${c.replay.branch}`);
    }
    sections.push("");
  }

  // Artifacts
  if (ast.artifacts.length > 0) {
    sections.push("## Artifacts");
    sections.push("");
    for (const art of ast.artifacts) {
      let line = `- **${art.id}** (${art.type})`;
      if (art.path) line += ` — path: ${art.path}`;
      if (art.retention) line += `, retention: ${art.retention}`;
      if (art.dependsOn && art.dependsOn.length > 0) line += `, depends on: ${art.dependsOn.join(", ")}`;
      sections.push(line);
    }
    sections.push("");
  }

  // Schemas
  if (ast.schemas.length > 0) {
    sections.push("## Schemas");
    sections.push("");
    for (const schema of ast.schemas) {
      sections.push(`### ${toTitle(schema.id)}`);
      for (const field of schema.fields) {
        sections.push(formatSchemaField(field));
      }
      sections.push("");
    }
  }

  // Composition: params
  if (ast.params && ast.params.length > 0) {
    sections.push("## Parameters");
    sections.push("");
    for (const p of ast.params) {
      const req = p.required ? " (required)" : "";
      const def = p.default != null ? ` = ${p.default}` : "";
      sections.push(`- **${p.name}**: ${p.type}${req}${def}`);
    }
    sections.push("");
  }

  // Composition: interface endpoints
  if (ast.interfaceEndpoints) {
    sections.push("## Interface");
    sections.push("");
    sections.push(`- Entry: ${ast.interfaceEndpoints.entry}`);
    sections.push(`- Exit: ${ast.interfaceEndpoints.exit}`);
    sections.push("");
  }

  // Composition: imports
  if (ast.imports && ast.imports.length > 0) {
    sections.push("## Imports");
    sections.push("");
    for (const imp of ast.imports) {
      let line = `- **${imp.alias}** from \`${imp.source}\``;
      if (imp.sha256) line += ` (sha256: ${imp.sha256})`;
      if (imp.registry) line += ` [registry: ${imp.registryPackage}@${imp.registryVersion}]`;
      sections.push(line);
      if (Object.keys(imp.params).length > 0) {
        for (const [k, v] of Object.entries(imp.params)) {
          sections.push(`  - ${k}: ${v}`);
        }
      }
    }
    sections.push("");
  }

  // Composition: includes
  if (ast.includes && ast.includes.length > 0) {
    sections.push("## Includes");
    sections.push("");
    for (const inc of ast.includes) {
      sections.push(`- ${inc.source}`);
    }
    sections.push("");
  }

  return {
    path: ".gemini/instructions.md",
    content: sections.join("\n") + "\n",
    category: "agent",
  };
}

/**
 * Generate .gemini/commands/<name>.md for each trigger.
 *
 * Gemini CLI supports custom commands defined as markdown files
 * in the .gemini/commands/ directory.
 */
function generateCommandFiles(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  for (const trigger of ast.triggers) {
    const sections: string[] = [];

    // Header
    sections.push(`# /${trigger.name}`);
    sections.push("");
    sections.push(trigger.pattern);
    sections.push("");

    // Arguments
    if (trigger.argument) {
      sections.push("## Arguments");
      sections.push(`- ${trigger.argument}: extracted from the command pattern`);
      sections.push("");
    }

    // Pipeline (from edges)
    if (ast.edges.length > 0) {
      sections.push("## Pipeline");
      for (const edge of ast.edges) {
        let line = `${edge.from} -> ${edge.to}`;
        if (edge.condition) line += ` [when ${edge.condition}]`;
        sections.push(`- ${line}`);
      }
      sections.push("");
    }

    // Agents table
    const agents = ast.nodes.filter((n) => n.type === "agent") as AgentNode[];
    if (agents.length > 0) {
      sections.push("## Agents");
      sections.push("| Agent | Phase | Model | Role |");
      sections.push("|-------|-------|-------|------|");
      for (const agent of agents) {
        const phase = agent.phase != null ? String(agent.phase) : "-";
        const model = agent.model ?? "-";
        const role = agent.role ?? "-";
        sections.push(`| ${agent.id} | ${phase} | ${model} | ${role} |`);
      }
      sections.push("");
    }

    files.push({
      path: `.gemini/commands/${trigger.name}.md`,
      content: sections.join("\n") + "\n",
      category: "machine",
    });
  }

  return files;
}

/** Generate gate script stubs. */
function generateGateScripts(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const name = ast.topology.name;

  for (const node of ast.nodes) {
    if (node.type !== "gate") continue;
    const gate = node as GateNode;
    if (gate.run) {
      const scriptName = gate.run.replace(/^.*\//, "").replace(/\s.*$/, "");
      files.push({
        path: `.gemini/scripts/${scriptName}`,
        content: shellStub(`Gate: ${gate.id} — ${gate.run}`),
        category: "script",
      });
    }
  }

  return files;
}

/** Generate hook script stubs. */
function generateHookScripts(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  for (const hook of ast.hooks) {
    if (!hook.run) continue;
    const scriptName = hook.run.replace(/^.*\//, "").replace(/\s.*$/, "");
    files.push({
      path: `.gemini/scripts/${scriptName}`,
      content: [
        "#!/usr/bin/env bash",
        `# Hook: ${hook.name} — fires on ${hook.on}`,
        "# Auto-generated by agentopology scaffold — edit as needed.",
        'set -euo pipefail',
        "",
        `echo "TODO: implement ${hook.name} hook"`,
        "",
      ].join("\n"),
      category: "script",
    });
  }

  return files;
}

/** Generate tool script stubs. */
function generateToolScripts(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  for (const tool of ast.toolDefs) {
    const ext = tool.lang === "python" ? "py" : tool.lang === "node" ? "js" : "sh";
    const shebang =
      tool.lang === "python"
        ? "#!/usr/bin/env python3"
        : tool.lang === "node"
          ? "#!/usr/bin/env node"
          : "#!/usr/bin/env bash";

    const lines = [
      shebang,
      `# Tool: ${tool.id} — ${tool.description}`,
      "# Auto-generated by agentopology scaffold — edit as needed.",
      "",
    ];

    if (tool.lang === "bash" || !tool.lang) {
      lines.push('set -euo pipefail');
      lines.push("");
    }

    if (tool.args && tool.args.length > 0) {
      lines.push(`# Args: ${tool.args.join(", ")}`);
      lines.push("");
    }

    lines.push(`echo "TODO: implement ${tool.id}"`);
    lines.push("");

    files.push({
      path: `.gemini/scripts/${tool.id}.${ext}`,
      content: lines.join("\n"),
      category: "script",
    });
  }

  return files;
}

/** Generate memory structure directories. */
function generateMemory(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const memory = ast.memory;

  if (memory.domains) {
    files.push(gitkeep(".gemini/context/domains"));
  }
  if (memory.references) {
    files.push(gitkeep(".gemini/context/references"));
  }
  if (memory.metrics) {
    files.push({
      path: ".gemini/metrics.jsonl",
      content: "",
      category: "machine",
    });
  }
  if (memory.workspace) {
    files.push(gitkeep(".gemini/workspace"));
  }

  return files;
}

/** Generate MCP server configuration. */
function generateMcpConfig(ast: TopologyAST): GeneratedFile | null {
  if (Object.keys(ast.mcpServers).length === 0) return null;

  const mcpConfig: Record<string, unknown> = { mcpServers: {} };
  const servers = mcpConfig.mcpServers as Record<string, unknown>;

  for (const [name, config] of Object.entries(ast.mcpServers)) {
    const entry: Record<string, unknown> = {};
    let hasEnv = false;
    for (const [key, value] of Object.entries(config)) {
      if (key === "args" && Array.isArray(value)) {
        entry.args = value;
      } else {
        entry[key] = value;
      }
      if (key === "env") hasEnv = true;
    }
    if (!hasEnv) {
      entry.env = {};
    }
    servers[name] = entry;
  }

  return {
    path: ".gemini/settings/mcp.json",
    content: JSON.stringify(mcpConfig, null, 2) + "\n",
    category: "machine",
  };
}

/** Generate metering script stub. */
function generateMetering(ast: TopologyAST): GeneratedFile | null {
  if (!ast.metering) return null;

  const m = ast.metering;
  const lines = [
    "#!/usr/bin/env bash",
    "# Metering / cost tracking script",
    "# Auto-generated by agentopology scaffold — edit as needed.",
    'set -euo pipefail',
    "",
    `# Track: ${m.track.join(", ")}`,
    `# Per: ${m.per.join(", ")}`,
    `# Output: ${m.output} (${m.format})`,
    `# Pricing: ${m.pricing}`,
    "",
    'echo "TODO: implement metrics collection"',
    "",
  ];

  return {
    path: "scripts/collect-metrics.sh",
    content: lines.join("\n"),
    category: "script",
  };
}

// ---------------------------------------------------------------------------
// Binding export
// ---------------------------------------------------------------------------

/** Google Gemini CLI binding. */
export const geminiCliBinding: BindingTarget = {
  name: "gemini-cli",
  description:
    "Google Gemini CLI — generates GEMINI.md, .gemini/ directory structure, and scripts.",

  scaffold(ast: TopologyAST): GeneratedFile[] {
    const files: GeneratedFile[] = [];

    // Main instructions file (.gemini/CONTEXT.md — never root GEMINI.md)
    files.push(generateGeminiMd(ast));

    // Settings file (permissions, tools, sandbox, env)
    files.push(generateSettings(ast));

    // Detailed project instructions
    files.push(generateInstructions(ast));

    // Command files from triggers
    files.push(...generateCommandFiles(ast));

    // Gate scripts
    files.push(...generateGateScripts(ast));

    // Hook scripts
    files.push(...generateHookScripts(ast));

    // Tool scripts
    files.push(...generateToolScripts(ast));

    // Memory directories
    files.push(...generateMemory(ast));

    // MCP server config
    const mcpFile = generateMcpConfig(ast);
    if (mcpFile) files.push(mcpFile);

    // Metering
    const meteringFile = generateMetering(ast);
    if (meteringFile) files.push(meteringFile);

    return deduplicateFiles(files);
  },
};
