/**
 * Kiro CLI binding.
 *
 * Generates the `.kiro/` directory structure, `AGENTS.md`, and supporting
 * files from a parsed {@link TopologyAST}.
 *
 * Kiro uses JSON-based agent definitions (`.kiro/agents/<id>.json`),
 * markdown steering documents (`.kiro/steering/`), and MCP configuration
 * (`.kiro/settings/mcp.json`). Unlike Claude Code where agents are markdown
 * files with frontmatter, Kiro agents are plain JSON.
 *
 * @module
 */

import type {
  TopologyAST,
  AgentNode,
  GateNode,
  GroupNode,
  HumanNode,
  OrchestratorNode,
  HookDef,
  SkillDef,
  ToolBlockDef,
  SchemaFieldDef,
  SchemaType,
  RetryConfig,
  CircuitBreakerConfig,
  PromptVariant,
} from "../parser/ast.js";
import { deduplicateFiles } from "./types.js";
import type { BindingTarget, GeneratedFile } from "./types.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Convert a kebab-case id to Title Case. */
function toTitle(id: string): string {
  return id
    .split(/[-_]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

/** Generate a shell script stub with a header comment. */
function shellStub(description: string): string {
  return [
    "#!/usr/bin/env bash",
    `# ${description}`,
    "# Auto-generated by agentopology scaffold — edit as needed.",
    "set -euo pipefail",
    "",
    'echo "TODO: implement this script"',
    "",
  ].join("\n");
}

/** Generate an empty directory marker (a .gitkeep file). */
function gitkeep(dirPath: string): GeneratedFile {
  return { path: `${dirPath}/.gitkeep`, content: "" };
}

/**
 * Map topology hook event names to Kiro event names.
 *
 * Kiro uses camelCase event names (preToolUse, postToolUse) instead of
 * PascalCase (PreToolUse, PostToolUse).
 */
function mapHookEvent(event: string): string {
  const eventMap: Record<string, string> = {
    PreToolUse: "preToolUse",
    PostToolUse: "postToolUse",
  };
  return eventMap[event] ?? event;
}

/**
 * Map topology tool names to Kiro tool names.
 *
 * Kiro uses lowercase tool names with fs_ prefixes for file operations.
 */
function mapToolName(tool: string): string {
  const toolMap: Record<string, string> = {
    Read: "read",
    Write: "write",
    Bash: "shell",
    Edit: "write",
  };
  return toolMap[tool] ?? tool.toLowerCase();
}

/**
 * Map topology tool names to Kiro hook matcher names.
 *
 * For hook matchers, Kiro uses the fs_read/fs_write/execute_bash convention.
 */
function mapMatcherName(matcher: string): string {
  const matcherMap: Record<string, string> = {
    Read: "fs_read",
    Write: "fs_write",
    Bash: "execute_bash",
    Edit: "fs_write",
  };
  return matcherMap[matcher] ?? matcher;
}

/** Format a SchemaType to a human-readable string. */
function formatSchemaType(t: SchemaType): string {
  switch (t.kind) {
    case "primitive":
      return t.value;
    case "array":
      return `${formatSchemaType(t.itemType)}[]`;
    case "enum":
      return t.values.join(" | ");
    case "ref":
      return t.name;
  }
}

/** Format schema fields as a markdown list. */
function formatSchemaFields(fields: SchemaFieldDef[]): string {
  return fields
    .map((f) => `- \`${f.name}${f.optional ? "?" : ""}\`: ${formatSchemaType(f.type)}`)
    .join("\n");
}

// ---------------------------------------------------------------------------
// Agent JSON generation
// ---------------------------------------------------------------------------

/**
 * Generate `.kiro/agents/<id>.json` for each agent node.
 *
 * Each agent produces a single JSON file with name, description, prompt,
 * model, tools, hooks, resources, and MCP configuration.
 */
function generateAgents(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  for (const node of ast.nodes) {
    if (node.type !== "agent") continue;
    const agent = node as AgentNode;

    const agentJson: Record<string, unknown> = {};
    agentJson.name = agent.id;

    // Description: prefer agent.description, then role description
    const desc =
      agent.description ??
      ast.roles[agent.role ?? ""] ??
      ast.roles[agent.id] ??
      agent.role;
    if (desc) {
      agentJson.description = desc;
    }

    // Prompt: build from role + inline prompt
    const promptParts: string[] = [];
    const roleText =
      ast.roles[agent.role ?? ""] ?? ast.roles[agent.id] ?? agent.role;
    if (roleText) {
      promptParts.push(`You are the ${toTitle(agent.id)} agent.\n\n## Role\n${roleText}`);
    } else {
      promptParts.push(`You are the ${toTitle(agent.id)} agent.`);
    }
    if (agent.prompt) {
      promptParts.push(`\n## Instructions\n\n${agent.prompt}`);
    }
    if (agent.reads && agent.reads.length > 0) {
      promptParts.push(`\n## Reads\n${agent.reads.map((r) => `- ${r}`).join("\n")}`);
    }
    if (agent.writes && agent.writes.length > 0) {
      promptParts.push(`\n## Writes\n${agent.writes.map((w) => `- ${w}`).join("\n")}`);
    }
    if (agent.outputs) {
      const outputLines = Object.entries(agent.outputs)
        .map(([field, values]) => `- ${field}: ${values.join(" | ")}`)
        .join("\n");
      promptParts.push(`\n## Outputs\n${outputLines}`);
    }
    if (agent.skills && agent.skills.length > 0) {
      promptParts.push(`\nSkills: ${agent.skills.join(", ")}`);
    }
    if (agent.behavior) {
      promptParts.push(`\nBehavior: ${agent.behavior}`);
    }
    if (agent.skip) {
      promptParts.push(`\nSkip when: ${agent.skip}`);
    }
    agentJson.prompt = promptParts.join("\n");

    // Model
    if (agent.model) {
      agentJson.model = agent.model;
    }

    // Timeout (Wave 1)
    if (agent.timeout) {
      agentJson.timeout = agent.timeout;
    }

    // Sampling params (Wave 1) — model config
    if (agent.temperature != null) {
      agentJson.temperature = agent.temperature;
    }
    if (agent.maxTokens != null) {
      agentJson.maxTokens = agent.maxTokens;
    }

    // Thinking/reasoning (Wave 1)
    if (agent.thinking) {
      agentJson.reasoning = agent.thinking;
    }

    // Max turns
    if (agent.maxTurns != null) {
      agentJson.maxTurns = agent.maxTurns;
    }

    // Tools — map topology tool names to Kiro names
    if (agent.tools && agent.tools.length > 0) {
      agentJson.tools = agent.tools.map(mapToolName);
    }

    // Allowed tools (subset that don't require confirmation)
    if (agent.extensions?.kiro?.allowedTools) {
      agentJson.allowedTools = agent.extensions.kiro.allowedTools;
    }

    // MCP servers as resources
    if (agent.mcpServers && agent.mcpServers.length > 0) {
      agentJson.resources = agent.mcpServers.map((s) => `mcp://${s}`);
    }

    // Reads as file:// resources
    if (agent.reads && agent.reads.length > 0) {
      const existing = (agentJson.resources as string[]) ?? [];
      agentJson.resources = [
        ...existing,
        ...agent.reads.map((r) => `file://${r}`),
      ];
    }

    // Per-agent hooks
    if (agent.hooks && agent.hooks.length > 0) {
      agentJson.hooks = agent.hooks.map((hook) => {
        const entry: Record<string, unknown> = {
          event: mapHookEvent(hook.on),
          command: hook.run,
        };
        if (hook.matcher) {
          entry.matcher = mapMatcherName(hook.matcher);
        }
        return entry;
      });
    }

    // Include MCP config if agent uses MCP servers
    if (agent.mcpServers && agent.mcpServers.length > 0) {
      agentJson.includeMcpJson = true;
    }

    // Merge kiro extension fields
    if (agent.extensions?.kiro) {
      const handled = new Set(["allowedTools"]);
      for (const [k, v] of Object.entries(agent.extensions.kiro)) {
        if (handled.has(k)) continue;
        agentJson[k] = v;
      }
    }

    files.push({
      path: `.kiro/agents/${agent.id}.json`,
      content: JSON.stringify(agentJson, null, 2) + "\n",
    });
  }

  return files;
}

// ---------------------------------------------------------------------------
// Per-agent steering docs for Wave 1-7 features
// ---------------------------------------------------------------------------

/**
 * Generate `.kiro/steering/agent-<id>.md` for agents with behavioral config
 * that cannot be expressed in JSON (on-fail, retry, circuitBreaker, schemas,
 * rate limits, artifacts, join semantics, output format, log level, variants).
 */
function generateAgentSteering(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  for (const node of ast.nodes) {
    if (node.type !== "agent") continue;
    const agent = node as AgentNode;

    const sections: string[] = [];
    let hasContent = false;

    // on-fail / retry (Wave 1)
    if (agent.onFail) {
      sections.push(`## Failure Handling`);
      sections.push("");
      sections.push(`On failure: **${agent.onFail}**`);
      sections.push("");
      hasContent = true;
    }
    if (agent.retry != null) {
      if (!sections.some((s) => s.includes("Failure Handling"))) {
        sections.push(`## Failure Handling`);
        sections.push("");
      }
      if (typeof agent.retry === "number") {
        sections.push(`Retry up to **${agent.retry}** times on failure.`);
      } else {
        const r = agent.retry as RetryConfig;
        sections.push(`Retry up to **${r.max}** times.`);
        if (r.backoff) sections.push(`- Backoff: ${r.backoff}`);
        if (r.interval) sections.push(`- Interval: ${r.interval}`);
        if (r.maxInterval) sections.push(`- Max interval: ${r.maxInterval}`);
        if (r.jitter) sections.push(`- Jitter: enabled`);
        if (r.nonRetryable && r.nonRetryable.length > 0) {
          sections.push(`- Non-retryable: ${r.nonRetryable.join(", ")}`);
        }
      }
      sections.push("");
      hasContent = true;
    }

    // circuitBreaker (Wave 5)
    if (agent.circuitBreaker) {
      const cb = agent.circuitBreaker;
      sections.push(`## Circuit Breaker`);
      sections.push("");
      sections.push(`- Threshold: ${cb.threshold} failures`);
      sections.push(`- Window: ${cb.window}`);
      sections.push(`- Cooldown: ${cb.cooldown}`);
      sections.push("");
      hasContent = true;
    }

    // compensates (Wave 5 — saga)
    if (agent.compensates) {
      sections.push(`## Compensation`);
      sections.push("");
      sections.push(`This agent compensates (undoes side effects of) **${agent.compensates}**.`);
      sections.push("");
      hasContent = true;
    }

    // inputSchema / outputSchema (Wave 3)
    if (agent.inputSchema && agent.inputSchema.length > 0) {
      sections.push(`## Input Schema`);
      sections.push("");
      sections.push(formatSchemaFields(agent.inputSchema));
      sections.push("");
      hasContent = true;
    }
    if (agent.outputSchema && agent.outputSchema.length > 0) {
      sections.push(`## Output Schema`);
      sections.push("");
      sections.push(formatSchemaFields(agent.outputSchema));
      sections.push("");
      hasContent = true;
    }

    // rateLimit (Wave 6)
    if (agent.rateLimit) {
      sections.push(`## Rate Limit`);
      sections.push("");
      sections.push(`Rate limit: **${agent.rateLimit}**`);
      sections.push("");
      hasContent = true;
    }

    // produces / consumes (Wave 6 — artifacts)
    if (agent.produces && agent.produces.length > 0) {
      sections.push(`## Produces`);
      sections.push("");
      sections.push(agent.produces.map((a) => `- ${a}`).join("\n"));
      sections.push("");
      hasContent = true;
    }
    if (agent.consumes && agent.consumes.length > 0) {
      sections.push(`## Consumes`);
      sections.push("");
      sections.push(agent.consumes.map((a) => `- ${a}`).join("\n"));
      sections.push("");
      hasContent = true;
    }

    // join (Wave 2)
    if (agent.join) {
      sections.push(`## Join Strategy`);
      sections.push("");
      sections.push(`Wait strategy: **${agent.join}**`);
      sections.push("");
      hasContent = true;
    }

    // outputFormat (Wave 1)
    if (agent.outputFormat) {
      sections.push(`## Output Format`);
      sections.push("");
      sections.push(`Expected output format: **${agent.outputFormat}**`);
      sections.push("");
      hasContent = true;
    }

    // logLevel (Wave 3)
    if (agent.logLevel) {
      sections.push(`## Log Level`);
      sections.push("");
      sections.push(`Log level: **${agent.logLevel}**`);
      sections.push("");
      hasContent = true;
    }

    // variants (Wave 7 — A/B testing)
    if (agent.variants && agent.variants.length > 0) {
      sections.push(`## Prompt Variants`);
      sections.push("");
      for (const v of agent.variants) {
        const parts = [`**${v.id}** (weight: ${v.weight})`];
        if (v.model) parts.push(`model: ${v.model}`);
        if (v.temperature != null) parts.push(`temperature: ${v.temperature}`);
        sections.push(`- ${parts.join(", ")}`);
        if (v.prompt) {
          sections.push(`  > ${v.prompt.replace(/\n/g, "\n  > ")}`);
        }
      }
      sections.push("");
      hasContent = true;
    }

    if (!hasContent) continue;

    const header = [
      "---",
      `inclusion: agent:${agent.id}`,
      "---",
      "",
      `# ${toTitle(agent.id)} — Behavioral Config`,
      "",
    ];

    files.push({
      path: `.kiro/steering/agent-${agent.id}.md`,
      content: header.join("\n") + sections.join("\n") + "\n",
    });
  }

  return files;
}

// ---------------------------------------------------------------------------
// Human node steering docs
// ---------------------------------------------------------------------------

/**
 * Generate `.kiro/steering/human-<id>.md` for human-in-the-loop pause points.
 */
function generateHumanSteering(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  for (const node of ast.nodes) {
    if (node.type !== "human") continue;
    const human = node as HumanNode;

    const sections: string[] = [
      "---",
      "inclusion: always",
      "---",
      "",
      `# ${toTitle(human.id)} — Human Pause Point`,
      "",
    ];

    if (human.description) {
      sections.push(human.description);
      sections.push("");
    }

    sections.push("## Behavior");
    sections.push("");
    sections.push("This is a human-in-the-loop pause point. Stop and wait for human input before continuing.");
    sections.push("");

    if (human.timeout) {
      sections.push(`- Timeout: ${human.timeout}`);
    }
    if (human.onTimeout) {
      sections.push(`- On timeout: ${human.onTimeout}`);
    }
    if (human.timeout || human.onTimeout) {
      sections.push("");
    }

    files.push({
      path: `.kiro/steering/human-${human.id}.md`,
      content: sections.join("\n") + "\n",
    });
  }

  return files;
}

// ---------------------------------------------------------------------------
// Group node steering docs
// ---------------------------------------------------------------------------

/**
 * Generate `.kiro/steering/group-<id>.md` for group chat coordination nodes.
 */
function generateGroupSteering(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  for (const node of ast.nodes) {
    if (node.type !== "group") continue;
    const group = node as GroupNode;

    const sections: string[] = [
      "---",
      "inclusion: always",
      "---",
      "",
      `# ${toTitle(group.id)} — Group Chat`,
      "",
    ];

    if (group.description) {
      sections.push(group.description);
      sections.push("");
    }

    sections.push("## Coordination");
    sections.push("");
    sections.push(`Members: ${group.members.join(", ")}`);
    if (group.speakerSelection) {
      sections.push(`Speaker selection: ${group.speakerSelection}`);
    }
    if (group.maxRounds != null) {
      sections.push(`Max rounds: ${group.maxRounds}`);
    }
    if (group.termination) {
      sections.push(`Termination: ${group.termination}`);
    }
    if (group.timeout) {
      sections.push(`Timeout: ${group.timeout}`);
    }
    sections.push("");

    files.push({
      path: `.kiro/steering/group-${group.id}.md`,
      content: sections.join("\n") + "\n",
    });
  }

  return files;
}

// ---------------------------------------------------------------------------
// Steering documents
// ---------------------------------------------------------------------------

/**
 * Generate `.kiro/steering/product.md` — product context with topology
 * description, version, and patterns.
 */
function generateProductSteering(ast: TopologyAST): GeneratedFile {
  const sections: string[] = [];

  sections.push("---");
  sections.push("inclusion: always");
  sections.push("---");
  sections.push("");
  sections.push("# Product Context");
  sections.push("");

  if (ast.topology.description) {
    sections.push(ast.topology.description);
    sections.push("");
  }

  sections.push(`Version: ${ast.topology.version}`);
  if (ast.topology.patterns.length > 0) {
    sections.push(`Patterns: ${ast.topology.patterns.join(", ")}`);
  }
  sections.push("");

  // Schedules
  if (ast.schedules && ast.schedules.length > 0) {
    sections.push("## Schedules");
    sections.push("");
    for (const job of ast.schedules) {
      const expr = job.cron
        ? `cron: ${job.cron}`
        : job.every
          ? `every: ${job.every}`
          : "";
      const target = job.agent
        ? `agent: ${job.agent}`
        : job.action
          ? `action: ${job.action}`
          : "";
      sections.push(
        `- **${job.id}**: ${expr}${target ? ` -> ${target}` : ""}${job.enabled === false ? " (disabled)" : ""}`
      );
    }
    sections.push("");
  }

  // Interfaces
  if (ast.interfaces && ast.interfaces.length > 0) {
    sections.push("## Interfaces");
    sections.push("");
    for (const iface of ast.interfaces) {
      const typePart = iface.type ? ` (${iface.type})` : "";
      const configKeys = Object.keys(iface.config);
      const configPart =
        configKeys.length > 0
          ? ` — ${configKeys.map((k) => `${k}: ${iface.config[k]}`).join(", ")}`
          : "";
      sections.push(`- **${iface.id}**${typePart}${configPart}`);
    }
    sections.push("");
  }

  return {
    path: ".kiro/steering/product.md",
    content: sections.join("\n") + "\n",
  };
}

/**
 * Generate `.kiro/steering/tech.md` — technology context with models,
 * tool configuration, and provider settings.
 */
function generateTechSteering(ast: TopologyAST): GeneratedFile {
  const sections: string[] = [];

  sections.push("---");
  sections.push("inclusion: always");
  sections.push("---");
  sections.push("");
  sections.push("# Technology");
  sections.push("");

  // Models used
  const models = new Set<string>();
  for (const node of ast.nodes) {
    if (node.type === "orchestrator") {
      models.add((node as OrchestratorNode).model);
    } else if (node.type === "agent" && (node as AgentNode).model) {
      models.add((node as AgentNode).model!);
    }
  }
  if (models.size > 0) {
    sections.push("## Models");
    sections.push("");
    for (const model of models) {
      sections.push(`- ${model}`);
    }
    sections.push("");
  }

  // Providers
  if (ast.providers && ast.providers.length > 0) {
    sections.push("## Providers");
    sections.push("");
    for (const p of ast.providers) {
      const parts = [p.name];
      if (p.baseUrl) parts.push(`base: ${p.baseUrl}`);
      if (p.default) parts.push("(default)");
      sections.push(`- ${parts.join(" — ")}`);
    }
    sections.push("");
  }

  // Tools
  if (ast.toolDefs.length > 0) {
    sections.push("## Tools");
    sections.push("");
    for (const tool of ast.toolDefs) {
      sections.push(`- **${tool.id}**: ${tool.description}`);
    }
    sections.push("");
  }

  // Skills summary
  if (ast.skills.length > 0) {
    sections.push("## Skills");
    sections.push("");
    for (const skill of ast.skills) {
      const desc = skill.description ? ` — ${skill.description}` : "";
      sections.push(`- **${skill.id}**${desc}`);
    }
    sections.push("");
  }

  // Environment variables
  if (Object.keys(ast.env).length > 0) {
    sections.push("## Environment");
    sections.push("");
    for (const [key, val] of Object.entries(ast.env)) {
      const value = typeof val === "string" ? val : val.value;
      sections.push(`- \`${key}\`: ${value}`);
    }
    sections.push("");
  }

  return {
    path: ".kiro/steering/tech.md",
    content: sections.join("\n") + "\n",
  };
}

/**
 * Generate `.kiro/steering/structure.md` — file organization with
 * memory layout and read/write patterns.
 */
function generateStructureSteering(ast: TopologyAST): GeneratedFile {
  const sections: string[] = [];

  sections.push("---");
  sections.push("inclusion: always");
  sections.push("---");
  sections.push("");
  sections.push("# Structure");
  sections.push("");

  // Memory layout
  if (Object.keys(ast.memory).length > 0) {
    sections.push("## Memory Layout");
    sections.push("");
    if (ast.memory.domains) {
      sections.push("- **Domains:** .kiro/domains/");
    }
    if (ast.memory.references) {
      sections.push("- **References:** .kiro/references/");
    }
    if (ast.memory.metrics) {
      sections.push("- **Metrics:** .kiro/metrics.jsonl");
    }
    if (ast.memory.workspace) {
      sections.push("- **Workspace:** .kiro/runs/");
    }
    sections.push("");
  }

  // Read/Write patterns
  const agents = ast.nodes.filter((n) => n.type === "agent") as AgentNode[];
  const agentsWithAccess = agents.filter(
    (a) => (a.reads && a.reads.length > 0) || (a.writes && a.writes.length > 0)
  );
  if (agentsWithAccess.length > 0) {
    sections.push("## Read/Write Patterns");
    sections.push("");
    for (const agent of agentsWithAccess) {
      sections.push(`### ${toTitle(agent.id)}`);
      if (agent.reads && agent.reads.length > 0) {
        sections.push(`- Reads: ${agent.reads.join(", ")}`);
      }
      if (agent.writes && agent.writes.length > 0) {
        sections.push(`- Writes: ${agent.writes.join(", ")}`);
      }
      sections.push("");
    }
  }

  // Workspace protocol
  const workspace = ast.memory.workspace as Record<string, unknown> | undefined;
  if (workspace?.structure && Array.isArray(workspace.structure)) {
    sections.push("## Workspace Structure");
    sections.push("");
    for (const item of workspace.structure) {
      sections.push(`- ${item}`);
    }
    sections.push("");
  }

  return {
    path: ".kiro/steering/structure.md",
    content: sections.join("\n") + "\n",
  };
}

// ---------------------------------------------------------------------------
// MCP configuration
// ---------------------------------------------------------------------------

/**
 * Generate `.kiro/settings/mcp.json` — MCP server configuration.
 *
 * Nearly identical to Claude Code's .mcp.json format: an object with a
 * `mcpServers` key mapping server names to their configuration.
 */
function generateMcpJson(ast: TopologyAST): GeneratedFile | null {
  if (Object.keys(ast.mcpServers).length === 0) return null;

  const mcpConfig: Record<string, unknown> = { mcpServers: {} };
  const servers = mcpConfig.mcpServers as Record<string, unknown>;

  for (const [name, config] of Object.entries(ast.mcpServers)) {
    const entry: Record<string, unknown> = {};
    let hasEnv = false;
    for (const [key, value] of Object.entries(config)) {
      if (key === "args" && Array.isArray(value)) {
        entry.args = value;
      } else {
        entry[key] = value;
      }
      if (key === "env") hasEnv = true;
    }
    // Always include env field
    if (!hasEnv) {
      entry.env = {};
    }
    servers[name] = entry;
  }

  return {
    path: ".kiro/settings/mcp.json",
    content: JSON.stringify(mcpConfig, null, 2) + "\n",
  };
}

// ---------------------------------------------------------------------------
// Trigger / prompt files
// ---------------------------------------------------------------------------

/**
 * Generate `.kiro/prompts/<trigger-name>.md` — one file per trigger.
 */
function generatePromptFiles(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  for (const trigger of ast.triggers) {
    const sections: string[] = [];

    sections.push(`# /${trigger.name}`);
    sections.push("");
    sections.push(trigger.pattern);
    sections.push("");

    if (trigger.argument) {
      sections.push("## Arguments");
      sections.push(`- ${trigger.argument}: extracted from the command pattern`);
      sections.push("");
    }

    // Pipeline (from edges)
    if (ast.edges.length > 0) {
      sections.push("## Pipeline");
      for (const edge of ast.edges) {
        let line = `${edge.from} -> ${edge.to}`;
        if (edge.condition) line += ` [when ${edge.condition}]`;
        sections.push(`- ${line}`);
      }
      sections.push("");
    }

    // Agents table
    const agents = ast.nodes.filter((n) => n.type === "agent") as AgentNode[];
    if (agents.length > 0) {
      sections.push("## Agents");
      sections.push("| Agent | Phase | Model | Role |");
      sections.push("|-------|-------|-------|------|");
      for (const agent of agents) {
        const phase = agent.phase != null ? String(agent.phase) : "-";
        const model = agent.model ?? "-";
        const role = agent.role ?? "-";
        sections.push(`| ${agent.id} | ${phase} | ${model} | ${role} |`);
      }
      sections.push("");
    }

    files.push({
      path: `.kiro/prompts/${trigger.name}.md`,
      content: sections.join("\n") + "\n",
    });
  }

  return files;
}

// ---------------------------------------------------------------------------
// AGENTS.md — top-level project context with flow narrative
// ---------------------------------------------------------------------------

/**
 * Generate `AGENTS.md` — top-level project context.
 *
 * Kiro has no native orchestration, so the flow graph is expressed as
 * prose in AGENTS.md to give the AI context about the multi-agent workflow.
 */
function generateAgentsMd(ast: TopologyAST): GeneratedFile {
  const sections: string[] = [];
  const name = ast.topology.name;

  sections.push(`# ${toTitle(name)} — Agent Topology`);
  sections.push("");
  if (ast.topology.description) {
    sections.push(ast.topology.description);
    sections.push("");
  }
  sections.push(`Version: ${ast.topology.version}`);
  if (ast.topology.patterns.length > 0) {
    sections.push(`Patterns: ${ast.topology.patterns.join(", ")}`);
  }
  sections.push("");

  // Orchestrator
  const orch = ast.nodes.find((n) => n.type === "orchestrator");
  if (orch) {
    sections.push("## Orchestrator");
    sections.push("");
    sections.push(`Model: ${(orch as OrchestratorNode).model}`);
    if ((orch as OrchestratorNode).handles?.length > 0) {
      sections.push(
        `Handles: ${(orch as OrchestratorNode).handles.join(", ")}`
      );
    }
    if ((orch as OrchestratorNode).generates) {
      sections.push(`Generates: ${(orch as OrchestratorNode).generates}`);
    }
    sections.push("");
  }

  // Flow (enhanced with Wave 2+ edge attributes)
  if (ast.edges.length > 0) {
    sections.push("## Flow");
    sections.push("");
    for (const edge of ast.edges) {
      const arrow = edge.isError ? `-x${edge.errorType ? `[${edge.errorType}]` : ""}->` : "->";
      let line = `${edge.from} ${arrow} ${edge.to}`;
      if (edge.condition) line += ` [when ${edge.condition}]`;
      if (edge.maxIterations) line += ` [max ${edge.maxIterations}]`;
      if (edge.weight != null) line += ` [weight ${edge.weight}]`;
      if (edge.race) line += ` [race]`;
      if (edge.tolerance != null) line += ` [tolerance: ${edge.tolerance}]`;
      if (edge.wait) line += ` [wait ${edge.wait}]`;
      if (edge.reflection) line += ` (reflection)`;
      sections.push(`- ${line}`);
    }
    sections.push("");
  }

  // Agent summary table
  const agents = ast.nodes.filter((n) => n.type === "agent") as AgentNode[];
  if (agents.length > 0) {
    sections.push("## Agents");
    sections.push("");
    for (const agent of agents) {
      sections.push(`### ${toTitle(agent.id)}`);
      sections.push("");

      const roleText =
        ast.roles[agent.role ?? ""] ?? ast.roles[agent.id] ?? agent.role;
      if (roleText) {
        sections.push(`**Role:** ${roleText}`);
        sections.push("");
      }
      if (agent.description) {
        sections.push(agent.description);
        sections.push("");
      }
      if (agent.model) {
        sections.push(`- **Model:** ${agent.model}`);
      }
      if (agent.phase != null) {
        sections.push(`- **Phase:** ${agent.phase}`);
      }
      if (agent.tools && agent.tools.length > 0) {
        sections.push(`- **Tools:** ${agent.tools.join(", ")}`);
      }
      if (agent.reads && agent.reads.length > 0) {
        sections.push(`- **Reads:** ${agent.reads.join(", ")}`);
      }
      if (agent.writes && agent.writes.length > 0) {
        sections.push(`- **Writes:** ${agent.writes.join(", ")}`);
      }
      if (agent.behavior) {
        sections.push(`- **Behavior:** ${agent.behavior}`);
      }
      sections.push("");
    }
  }

  // Gates
  const gates = ast.nodes.filter((n) => n.type === "gate") as GateNode[];
  if (gates.length > 0) {
    sections.push("## Gates");
    sections.push("");
    for (const gate of gates) {
      sections.push(`### ${toTitle(gate.id)}`);
      if (gate.after) sections.push(`After: ${gate.after}`);
      if (gate.before) sections.push(`Before: ${gate.before}`);
      if (gate.run) sections.push(`Run: ${gate.run}`);
      if (gate.checks && gate.checks.length > 0) {
        sections.push(`Checks: ${gate.checks.join(", ")}`);
      }
      if (gate.onFail) sections.push(`On fail: ${gate.onFail}`);
      sections.push("");
    }
  }

  // Human nodes
  const humans = ast.nodes.filter((n) => n.type === "human") as HumanNode[];
  if (humans.length > 0) {
    sections.push("## Human Pause Points");
    sections.push("");
    for (const human of humans) {
      sections.push(`### ${toTitle(human.id)}`);
      if (human.description) sections.push(human.description);
      if (human.timeout) sections.push(`- **Timeout:** ${human.timeout}`);
      if (human.onTimeout) sections.push(`- **On timeout:** ${human.onTimeout}`);
      sections.push("");
    }
  }

  // Group nodes
  const groups = ast.nodes.filter((n) => n.type === "group") as GroupNode[];
  if (groups.length > 0) {
    sections.push("## Group Chats");
    sections.push("");
    for (const group of groups) {
      sections.push(`### ${toTitle(group.id)}`);
      if (group.description) sections.push(group.description);
      sections.push(`- **Members:** ${group.members.join(", ")}`);
      if (group.speakerSelection) sections.push(`- **Speaker selection:** ${group.speakerSelection}`);
      if (group.maxRounds != null) sections.push(`- **Max rounds:** ${group.maxRounds}`);
      if (group.termination) sections.push(`- **Termination:** ${group.termination}`);
      if (group.timeout) sections.push(`- **Timeout:** ${group.timeout}`);
      sections.push("");
    }
  }

  // Triggers
  if (ast.triggers.length > 0) {
    sections.push("## Triggers");
    sections.push("");
    for (const trigger of ast.triggers) {
      sections.push(`### /${trigger.name}`);
      sections.push(`Pattern: \`${trigger.pattern}\``);
      if (trigger.argument) sections.push(`Argument: ${trigger.argument}`);
      sections.push("");
    }
  }

  return {
    path: "AGENTS.md",
    content: sections.join("\n") + "\n",
  };
}

// ---------------------------------------------------------------------------
// Hook scripts
// ---------------------------------------------------------------------------

/** Generate hook script stubs under .kiro/scripts/. */
function generateHookScripts(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  for (const hook of ast.hooks) {
    if (!hook.run) continue;
    const scriptName = hook.run.replace(/^.*\//, "").replace(/\s.*$/, "");
    files.push({
      path: `.kiro/scripts/${scriptName}`,
      content: [
        "#!/usr/bin/env bash",
        `# Hook: ${hook.name} — fires on ${mapHookEvent(hook.on)}`,
        "# Auto-generated by agentopology scaffold — edit as needed.",
        "set -euo pipefail",
        "",
        `echo "TODO: implement ${hook.name} hook"`,
        "",
      ].join("\n"),
    });
  }

  return files;
}

// ---------------------------------------------------------------------------
// Gate scripts
// ---------------------------------------------------------------------------

/** Generate gate script stubs under .kiro/scripts/. */
function generateGateScripts(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  for (const node of ast.nodes) {
    if (node.type !== "gate") continue;
    const gate = node as GateNode;
    if (gate.run) {
      const scriptName = gate.run.replace(/^.*\//, "").replace(/\s.*$/, "");
      files.push({
        path: `.kiro/scripts/${scriptName}`,
        content: shellStub(`Gate: ${gate.id} — ${gate.run}`),
      });
    }
  }

  return files;
}

// ---------------------------------------------------------------------------
// Tool scripts
// ---------------------------------------------------------------------------

/** Generate tool script stubs under .kiro/scripts/. */
function generateToolScripts(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  for (const tool of ast.toolDefs) {
    const ext =
      tool.lang === "python" ? "py" : tool.lang === "node" ? "js" : "sh";
    const shebang =
      tool.lang === "python"
        ? "#!/usr/bin/env python3"
        : tool.lang === "node"
          ? "#!/usr/bin/env node"
          : "#!/usr/bin/env bash";

    const lines = [
      shebang,
      `# Tool: ${tool.id} — ${tool.description}`,
      "# Auto-generated by agentopology scaffold — edit as needed.",
      "",
    ];

    if (tool.lang === "bash" || !tool.lang) {
      lines.push("set -euo pipefail");
      lines.push("");
    }

    if (tool.args && tool.args.length > 0) {
      lines.push(`# Args: ${tool.args.join(", ")}`);
      lines.push("");
    }

    lines.push(`echo "TODO: implement ${tool.id}"`);
    lines.push("");

    files.push({
      path: `.kiro/scripts/${tool.id}.${ext}`,
      content: lines.join("\n"),
    });
  }

  return files;
}

// ---------------------------------------------------------------------------
// Memory directories
// ---------------------------------------------------------------------------

/** Generate memory structure directories under .kiro/. */
function generateMemory(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  if (ast.memory.domains) {
    files.push(gitkeep(".kiro/domains"));
  }
  if (ast.memory.references) {
    files.push(gitkeep(".kiro/references"));
  }
  if (ast.memory.metrics) {
    files.push({
      path: ".kiro/metrics.jsonl",
      content: "",
    });
  }
  if (ast.memory.workspace) {
    files.push(gitkeep(".kiro/runs"));
  }

  return files;
}

// ---------------------------------------------------------------------------
// Metering script
// ---------------------------------------------------------------------------

/** Generate metering script stub. */
function generateMetering(ast: TopologyAST): GeneratedFile | null {
  if (!ast.metering) return null;

  const m = ast.metering;
  const lines = [
    "#!/usr/bin/env bash",
    "# Metering / cost tracking script",
    "# Auto-generated by agentopology scaffold — edit as needed.",
    "set -euo pipefail",
    "",
    `# Track: ${m.track.join(", ")}`,
    `# Per: ${m.per.join(", ")}`,
    `# Output: ${m.output} (${m.format})`,
    `# Pricing: ${m.pricing}`,
    "",
    'echo "TODO: implement metrics collection"',
    "",
  ];

  return {
    path: "scripts/collect-metrics.sh",
    content: lines.join("\n"),
  };
}

// ---------------------------------------------------------------------------
// Gate hooks
// ---------------------------------------------------------------------------

/**
 * Generate `.kiro/hooks/gate-{id}.md` files for each enforced gate.
 *
 * Kiro hooks are individual files in `.kiro/hooks/` with trigger metadata.
 * Each gate with `run:` and non-advisory behavior gets a hook file that
 * fires after the gate's `after` agent completes.
 */
function generateGateHooks(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  for (const node of ast.nodes) {
    if (node.type !== "gate") continue;
    const gate = node as GateNode;
    if (!gate.run) continue;
    if (gate.behavior === "advisory") continue;

    const scriptName = gate.run.replace(/^.*\//, "").replace(/\s.*$/, "");
    const onFail = gate.onFail || "halt";

    const triggerObj: Record<string, unknown> = {
      type: "postToolUse",
      matcher: gate.after || "*",
    };
    if (gate.timeout) {
      triggerObj.timeout = gate.timeout;
    }

    const content = [
      `# Gate: ${gate.id}`,
      "",
      "## Trigger",
      "",
      "```json",
      JSON.stringify(triggerObj, null, 2),
      "```",
      "",
      "## Description",
      "",
      `Quality gate that runs after **${gate.after || "any agent"}**${gate.before ? ` and before **${gate.before}**` : ""}.`,
      "",
      "## Action",
      "",
      `Run: \`bash .kiro/scripts/${scriptName}\``,
      "",
      `On failure: **${onFail}**`,
      "",
      gate.checks && gate.checks.length > 0
        ? `Checks: ${gate.checks.join(", ")}`
        : "",
      "",
    ].filter(Boolean).join("\n") + "\n";

    files.push({
      path: `.kiro/hooks/gate-${gate.id}.md`,
      content,
    });
  }

  return files;
}

// ---------------------------------------------------------------------------
// Binding export
// ---------------------------------------------------------------------------

/** Kiro CLI binding — generates .kiro/ directory structure and AGENTS.md. */
export const kiroBinding: BindingTarget = {
  name: "kiro",
  description:
    "AWS Kiro CLI — generates .kiro/ directory with JSON agents, steering docs, MCP config, and prompts.",

  scaffold(ast: TopologyAST): GeneratedFile[] {
    const files: GeneratedFile[] = [];

    // 1. Agent JSON files
    files.push(...generateAgents(ast));

    // 2. Steering documents
    files.push(generateProductSteering(ast));
    files.push(generateTechSteering(ast));
    files.push(generateStructureSteering(ast));

    // 2b. Per-agent behavioral steering docs (Wave 1-7)
    files.push(...generateAgentSteering(ast));

    // 2c. Human node steering docs (Wave 5)
    files.push(...generateHumanSteering(ast));

    // 2d. Group node steering docs (Wave 5)
    files.push(...generateGroupSteering(ast));

    // 3. MCP configuration
    const mcpFile = generateMcpJson(ast);
    if (mcpFile) files.push(mcpFile);

    // 4. Prompt files (triggers)
    files.push(...generatePromptFiles(ast));

    // 5. AGENTS.md (top-level flow narrative)
    files.push(generateAgentsMd(ast));

    // 6. Hook scripts
    files.push(...generateHookScripts(ast));

    // 7. Gate scripts
    files.push(...generateGateScripts(ast));

    // 8. Gate hook files
    files.push(...generateGateHooks(ast));

    // 9. Tool scripts
    files.push(...generateToolScripts(ast));

    // 10. Memory directories
    files.push(...generateMemory(ast));

    // 11. Metering
    const meteringFile = generateMetering(ast);
    if (meteringFile) files.push(meteringFile);

    return deduplicateFiles(files);
  },
};
