/**
 * OpenClaw binding.
 *
 * Generates a complete OpenClaw workspace from a parsed {@link TopologyAST}:
 * openclaw.json, SOUL.md, AGENTS.md, TOOLS.md, MEMORY.md, BOOTSTRAP.md,
 * TEAM.md, skill directories, gate/hook scripts, and workspace structure.
 *
 * OpenClaw is a multi-channel AI agent framework with gateway, channels,
 * and markdown-based agent identity. This binding adds security hardening
 * (auth required by default), quality gates, bounded loops, structured
 * metrics, and workspace access control that OpenClaw lacks natively.
 *
 * @module
 */

import type {
  TopologyAST,
  AgentNode,
  GateNode,
  OrchestratorNode,
} from "../parser/ast.js";
import type { BindingTarget, GeneratedFile } from "./types.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Convert a kebab-case id to Title Case. */
function toTitle(id: string): string {
  return id
    .split(/[-_]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

/** Generate a shell script stub with a header comment. */
function shellStub(description: string): string {
  return [
    "#!/usr/bin/env bash",
    `# ${description}`,
    "# Auto-generated by agentopology scaffold — edit as needed.",
    "set -euo pipefail",
    "",
    'echo "TODO: implement this script"',
    "",
  ].join("\n");
}

/** Generate an empty directory marker (a .gitkeep file). */
function gitkeep(dirPath: string): GeneratedFile {
  return { path: `${dirPath}/.gitkeep`, content: "" };
}

/**
 * Map topology model strings to OpenClaw model identifiers.
 */
function mapModel(model: string): string {
  const MODEL_MAP: Record<string, string> = {
    opus: "claude-opus-4",
    sonnet: "claude-sonnet-4.5",
    haiku: "claude-haiku-4",
  };
  return MODEL_MAP[model] ?? model;
}

/**
 * Map topology permission strings to OpenClaw permission labels.
 */
function mapPermissions(perm: string): string {
  switch (perm) {
    case "auto":
      return "autonomous";
    case "plan":
      return "supervised";
    case "confirm":
      return "interactive";
    case "bypass":
    case "bypassPermissions":
      return "unrestricted";
    case "supervised":
    case "autonomous":
    case "interactive":
    case "unrestricted":
      return perm;
    default:
      return "autonomous";
  }
}

/**
 * Extract openclaw-specific extension fields from the topology settings.
 */
function getOpenClawExtensions(
  ast: TopologyAST,
): Record<string, unknown> | null {
  const settingsExt = ast.settings?.extensions as
    | Record<string, Record<string, unknown>>
    | undefined;
  if (settingsExt?.openclaw) return settingsExt.openclaw;
  return null;
}

/** Get the orchestrator node from AST nodes. */
function getOrchestrator(ast: TopologyAST): OrchestratorNode | undefined {
  return ast.nodes.find((n) => n.type === "orchestrator") as
    | OrchestratorNode
    | undefined;
}

/** Get all agent nodes from AST, sorted by phase. */
function getAgentsSorted(ast: TopologyAST): AgentNode[] {
  const agents = ast.nodes.filter((n) => n.type === "agent") as AgentNode[];
  return agents.sort((a, b) => (a.phase ?? 0) - (b.phase ?? 0));
}

/** Get all gate nodes from AST. */
function getGates(ast: TopologyAST): GateNode[] {
  return ast.nodes.filter((n) => n.type === "gate") as GateNode[];
}

// ---------------------------------------------------------------------------
// File generators
// ---------------------------------------------------------------------------

/** Generate openclaw.json — central system config. */
function generateOpenClawJson(ast: TopologyAST): GeneratedFile {
  const ext = getOpenClawExtensions(ast);
  const orchestrator = getOrchestrator(ast);
  const agents = getAgentsSorted(ast);

  // Build agent list for config
  const agentList: Record<string, unknown>[] = [];

  // Orchestrator as primary agent
  if (orchestrator) {
    const agentIds = agents.map((a) => a.id);
    agentList.push({
      id: "orchestrator",
      name: toTitle(ast.topology.name) + " Coordinator",
      model: mapModel(orchestrator.model),
      workspace: `~/.openclaw/workspace-${ast.topology.name}`,
      agentDir: `./config/agents/orchestrator/agent`,
      subagents: {
        allowAgents: agentIds,
      },
    });
  }

  // Each agent node
  for (const agent of agents) {
    const entry: Record<string, unknown> = {
      id: agent.id,
      name: toTitle(agent.id),
      model: mapModel(agent.model ?? "sonnet"),
      workspace: `~/.openclaw/workspace-${agent.id}`,
      agentDir: `./config/agents/${agent.id}/agent`,
    };

    // Tools
    const allow = agent.tools ?? [];
    const deny = agent.disallowedTools ?? [];
    if (allow.length > 0 || deny.length > 0) {
      entry.tools = { allow, deny };
    }

    // Merge agent-level openclaw extensions
    if (agent.extensions?.openclaw) {
      for (const [k, v] of Object.entries(agent.extensions.openclaw)) {
        entry[k] = v;
      }
    }

    agentList.push(entry);
  }

  // Build config object
  const config: Record<string, unknown> = {
    name: ast.topology.name,
    version: ast.topology.version,
    agents: { list: agentList },
    gateway: {
      port: (ext?.["gateway-port"] as number) ?? 18789,
      auth: {
        requireToken: true, // HARDENED BY DEFAULT
        tokens: (ext?.["auth-tokens"] as string[]) ?? ["${OPENCLAW_AUTH_TOKEN}"],
      },
    },
  };

  // Channels from extensions
  if (ext?.channels) {
    const channelConfig: Record<string, unknown> = {
      enabled: ext.channels,
    };
    // Include per-channel config
    const channelNames = ext.channels as string[];
    if (Array.isArray(channelNames)) {
      for (const ch of channelNames) {
        if (ext[ch]) {
          channelConfig[ch] = ext[ch];
        }
      }
    }
    config.channels = channelConfig;
  }

  // Model fallback chain
  if (ext?.["model-fallback-chain"]) {
    const chain = ext["model-fallback-chain"] as string[];
    config.modelFallbackChain = chain.map(mapModel);
  }

  // Cron jobs
  if (ext?.["cron-jobs"]) {
    config.cronJobs = ext["cron-jobs"];
  }

  // Plugins
  if (ext?.plugins) {
    config.plugins = ext.plugins;
  }

  // Sandbox defaults
  if (ext?.["sandbox-defaults"]) {
    config.sandboxDefaults = ext["sandbox-defaults"];
  }

  // Node pairing
  if (ext?.["node-pairing"]) {
    config.nodePairing = ext["node-pairing"];
  }

  // Providers — API credentials and model routing
  if (ast.providers && ast.providers.length > 0) {
    const providersList: Record<string, unknown>[] = [];
    for (const p of ast.providers) {
      const entry: Record<string, unknown> = { name: p.name };
      if (p.apiKey) entry.apiKey = p.apiKey;
      if (p.baseUrl) entry.baseUrl = p.baseUrl;
      if (p.models.length > 0) entry.models = p.models.map(mapModel);
      if (p.default) entry.default = true;
      // Merge extra fields
      for (const [k, v] of Object.entries(p.extra)) {
        entry[k] = v;
      }
      providersList.push(entry);
    }
    config.providers = providersList;

    // Build model fallback chain from provider model lists if not already set
    if (!config.modelFallbackChain) {
      const defaultProvider = ast.providers.find((p) => p.default);
      if (defaultProvider && defaultProvider.models.length > 0) {
        config.modelFallbackChain = defaultProvider.models.map(mapModel);
      }
    }
  }

  // MCP servers
  if (Object.keys(ast.mcpServers).length > 0) {
    config.mcpServers = ast.mcpServers;
  }

  // Tools settings
  const settings = ast.settings;
  config.tools = {
    agentToAgent: { enabled: true },
    defaults: {
      allow: (settings?.allow as string[]) ?? [],
      deny: (settings?.deny as string[]) ?? [],
    },
  };

  return {
    path: "openclaw.json",
    content: JSON.stringify(config, null, 2) + "\n",
  };
}

/** Generate SOUL.md — primary agent identity. */
function generateSoulMd(ast: TopologyAST): GeneratedFile {
  const orchestrator = getOrchestrator(ast);
  const sections: string[] = [];

  // Quote block with description
  if (ast.topology.description) {
    sections.push(`> ${ast.topology.description}`);
    sections.push("");
  }

  // Identity
  sections.push("## Identity");
  sections.push(`- Name: ${toTitle(ast.topology.name)}`);
  sections.push(`- Version: ${ast.topology.version}`);
  if (orchestrator) {
    sections.push(`- Model: ${mapModel(orchestrator.model)}`);
  }
  if (ast.topology.patterns.length > 0) {
    sections.push(`- Patterns: ${ast.topology.patterns.join(", ")}`);
  }
  sections.push("");

  // Mission
  sections.push("## Mission");
  const mission = ast.topology.description ?? "Coordinate agent topology.";
  sections.push(mission);
  sections.push("");

  // Roles
  if (Object.keys(ast.roles).length > 0) {
    sections.push("## Roles");
    for (const [roleName, roleDesc] of Object.entries(ast.roles)) {
      sections.push(`### ${toTitle(roleName)}`);
      sections.push(roleDesc);
      sections.push("");
    }
  }

  // Ethical guardrails
  sections.push("## Ethical Guardrails");
  if (orchestrator) {
    sections.push(
      `- Permission model: ${mapPermissions((orchestrator as any).permissions ?? "auto")}`,
    );
  }
  const deny = ast.settings?.deny as string[] | undefined;
  sections.push(`- Tool restrictions: ${deny && deny.length > 0 ? deny.join(", ") : "none"}`);
  sections.push("");

  return {
    path: "SOUL.md",
    content: sections.join("\n") + "\n",
  };
}

/** Generate AGENTS.md — sub-agent definitions + flow orchestration logic. */
function generateAgentsMd(ast: TopologyAST): GeneratedFile {
  const agents = getAgentsSorted(ast);
  const gates = getGates(ast);
  const sections: string[] = [];

  // Header
  sections.push("# Sub-Agent Definitions");
  sections.push("");

  // Pipeline overview
  sections.push("## Pipeline Overview");
  sections.push(
    `${toTitle(ast.topology.name)} uses a ${ast.topology.patterns.join(" + ")} topology.`,
  );
  sections.push("");

  // Agents
  if (agents.length > 0) {
    sections.push("## Agents");
    sections.push("");

    for (const agent of agents) {
      sections.push(`### ${toTitle(agent.id)}`);
      sections.push(`- **Model:** ${mapModel(agent.model ?? "sonnet")}`);
      if (agent.phase != null) {
        sections.push(`- **Phase:** ${agent.phase}`);
      }

      // Role
      const roleText =
        ast.roles[agent.role ?? ""] ?? ast.roles[agent.id] ?? agent.role;
      if (roleText) {
        sections.push(`- **Role:** ${roleText}`);
      }

      // Tools
      if (agent.tools && agent.tools.length > 0) {
        sections.push(`- **Tools:** ${agent.tools.join(", ")}`);
      }

      // Memory access
      if (agent.reads && agent.reads.length > 0) {
        sections.push(`- **Reads:** ${agent.reads.join(", ")}`);
      }
      if (agent.writes && agent.writes.length > 0) {
        sections.push(`- **Writes:** ${agent.writes.join(", ")}`);
      }

      // Outputs
      if (agent.outputs) {
        sections.push("- **Outputs:**");
        for (const [field, values] of Object.entries(agent.outputs)) {
          sections.push(`  - ${field}: ${values.join(" | ")}`);
        }
      }

      // Scale
      if (agent.scale) {
        sections.push(
          `- **Scale:** ${agent.scale.min}-${agent.scale.max} instances by ${agent.scale.by}`,
        );
      }

      // Max turns
      if (agent.maxTurns != null) {
        sections.push(`- **Max turns:** ${agent.maxTurns}`);
      }

      // Skills
      if (agent.skills && agent.skills.length > 0) {
        sections.push(`- **Skills:** ${agent.skills.join(", ")}`);
      }

      // Description
      if (agent.description) {
        sections.push("");
        sections.push(agent.description);
      }

      if (agent.prompt) {
        sections.push("");
        sections.push("#### Instructions");
        sections.push("");
        sections.push(agent.prompt);
      }

      // OpenClaw-specific extensions
      if (agent.extensions?.openclaw) {
        sections.push("- **OpenClaw config:**");
        for (const [k, v] of Object.entries(agent.extensions.openclaw)) {
          sections.push(`  - ${k}: ${v}`);
        }
      }

      sections.push("");
    }
  }

  // Flow
  if (ast.edges.length > 0) {
    sections.push("## Flow");
    sections.push("");

    // Execution order
    sections.push("### Execution Order");
    let idx = 1;
    for (const edge of ast.edges) {
      let line = `${idx}. ${edge.from} -> ${edge.to}`;
      if (edge.condition) line += ` when ${edge.condition}`;
      if (edge.maxIterations) line += ` (max ${edge.maxIterations} iterations)`;
      sections.push(line);
      idx++;
    }
    sections.push("");

    // Conditional routing
    const conditionalEdges = ast.edges.filter((e) => e.condition);
    if (conditionalEdges.length > 0) {
      sections.push("### Conditional Routing");
      for (const edge of conditionalEdges) {
        sections.push(`- If ${edge.condition}: route to ${edge.to}`);
      }
      sections.push("");
    }

    // Fan-out points (nodes with multiple outgoing edges)
    const fromCounts: Record<string, string[]> = {};
    for (const edge of ast.edges) {
      if (!fromCounts[edge.from]) fromCounts[edge.from] = [];
      fromCounts[edge.from].push(edge.to);
    }
    const fanOutNodes = Object.entries(fromCounts).filter(
      ([, targets]) => targets.length > 1,
    );
    if (fanOutNodes.length > 0) {
      sections.push("### Fan-Out Points");
      for (const [from, targets] of fanOutNodes) {
        sections.push(
          `- After ${from}: spawn [${targets.join(", ")}] in parallel`,
        );
      }
      sections.push("");
    }

    // Bounded loops
    const boundedEdges = ast.edges.filter((e) => e.maxIterations);
    if (boundedEdges.length > 0) {
      sections.push("### Bounded Loops");
      for (const edge of boundedEdges) {
        sections.push(
          `- ${edge.from} <-> ${edge.to}: max ${edge.maxIterations} iterations (prevents infinite loops)`,
        );
      }
      sections.push("");
    }
  }

  // Gates
  if (gates.length > 0) {
    sections.push("## Gates");
    sections.push("");
    for (const gate of gates) {
      sections.push(`### ${toTitle(gate.id)}`);
      if (gate.after) sections.push(`- **After:** ${gate.after}`);
      if (gate.before) sections.push(`- **Before:** ${gate.before}`);
      if (gate.run) sections.push(`- **Script:** ${gate.run}`);
      if (gate.onFail) sections.push(`- **On failure:** ${gate.onFail}`);
      sections.push(`- **Behavior:** ${gate.behavior ?? "blocking"}`);
      if (gate.checks && gate.checks.length > 0) {
        sections.push(`- **Checks:** ${gate.checks.join(", ")}`);
      }
      sections.push("");
    }
  }

  return {
    path: "AGENTS.md",
    content: sections.join("\n") + "\n",
  };
}

/** Generate TOOLS.md — available tools + skill references. */
function generateToolsMd(ast: TopologyAST): GeneratedFile {
  const agents = getAgentsSorted(ast);
  const sections: string[] = [];

  sections.push("# Available Tools");
  sections.push("");

  // Core tools — unique tools across all agents
  const allTools = new Set<string>();
  for (const agent of agents) {
    if (agent.tools) {
      for (const t of agent.tools) allTools.add(t);
    }
  }
  if (allTools.size > 0) {
    sections.push("## Core Tools");
    sections.push("");
    for (const tool of allTools) {
      sections.push(`- ${tool}`);
    }
    sections.push("");
  }

  // Custom tools from toolDefs
  if (ast.toolDefs.length > 0) {
    sections.push("## Custom Tools");
    sections.push("");
    for (const tool of ast.toolDefs) {
      sections.push(`### ${tool.id}`);
      sections.push(tool.description);
      sections.push(`- Script: ${tool.script}`);
      if (tool.args && tool.args.length > 0) {
        sections.push(`- Args: ${tool.args.join(", ")}`);
      }
      if (tool.lang) {
        sections.push(`- Language: ${tool.lang}`);
      }
      sections.push("");
    }
  }

  // Skills
  if (ast.skills.length > 0) {
    sections.push("## Skills");
    sections.push("");
    for (const skill of ast.skills) {
      sections.push(`### ${skill.id}`);
      if (skill.description) {
        sections.push(skill.description);
      }
      sections.push("");
    }
  }

  return {
    path: "TOOLS.md",
    content: sections.join("\n") + "\n",
  };
}

/** Generate MEMORY.md — long-term memory structure. */
function generateMemoryMd(ast: TopologyAST): GeneratedFile {
  const agents = getAgentsSorted(ast);
  const memory = ast.memory;
  const sections: string[] = [];

  sections.push("# Memory Structure");
  sections.push("");

  // Domains
  const domains = memory.domains as Record<string, unknown> | undefined;
  if (domains) {
    sections.push("## Domains");
    if (domains.path) sections.push(`Path: ${domains.path}`);
    if (domains.routing) sections.push(`Routing: ${domains.routing}`);
    sections.push("");
  }

  // Workspace
  const workspace = memory.workspace as Record<string, unknown> | undefined;
  if (workspace) {
    sections.push("## Workspace");
    if (workspace.path) sections.push(`Path: ${workspace.path}`);
    if (workspace.structure && Array.isArray(workspace.structure)) {
      sections.push(`Structure: ${(workspace.structure as string[]).join(", ")}`);
    }
    sections.push("");
  }

  // Metrics
  const metrics = memory.metrics as Record<string, unknown> | undefined;
  if (metrics) {
    sections.push("## Metrics");
    if (metrics.path) sections.push(`Path: ${metrics.path}`);
    if (metrics.mode) sections.push(`Mode: ${metrics.mode}`);
    sections.push("");
  }

  // Agent access rules
  const agentsWithAccess = agents.filter(
    (a) =>
      (a.reads && a.reads.length > 0) || (a.writes && a.writes.length > 0),
  );
  if (agentsWithAccess.length > 0) {
    sections.push("## Agent Access Rules");
    sections.push("");
    for (const agent of agentsWithAccess) {
      sections.push(`### ${agent.id}`);
      if (agent.reads && agent.reads.length > 0) {
        sections.push(`- Reads: ${agent.reads.join(", ")}`);
      }
      if (agent.writes && agent.writes.length > 0) {
        sections.push(`- Writes: ${agent.writes.join(", ")}`);
      }
      sections.push("");
    }
  }

  return {
    path: "MEMORY.md",
    content: sections.join("\n") + "\n",
  };
}

/** Generate BOOTSTRAP.md — init instructions from hooks + gates. */
function generateBootstrapMd(ast: TopologyAST): GeneratedFile {
  const agents = getAgentsSorted(ast);
  const gates = getGates(ast);
  const sections: string[] = [];

  sections.push("# Bootstrap Sequence");
  sections.push("");

  // Initialization hooks
  const initHooks = ast.hooks.filter(
    (h) => h.on === "SessionStart" || h.on === "InstructionsLoaded",
  );
  if (initHooks.length > 0) {
    sections.push("## Initialization");
    let idx = 1;
    for (const hook of initHooks) {
      sections.push(`${idx}. Run: ${hook.run}`);
      idx++;
    }
    sections.push("");
  }

  // Pre-flight gates (gates before the first flow node)
  const firstEdge = ast.edges.length > 0 ? ast.edges[0] : null;
  const preFlightGates = gates.filter(
    (g) => firstEdge && g.before === firstEdge.from,
  );
  if (preFlightGates.length > 0) {
    sections.push("## Pre-Flight Gates");
    let idx = 1;
    for (const gate of preFlightGates) {
      sections.push(`${idx}. Gate: ${gate.id} -- ${gate.run ?? "manual check"}`);
      sections.push(`   On failure: ${gate.onFail ?? "halt"}`);
      idx++;
    }
    sections.push("");
  }

  // Agent initialization order
  if (agents.length > 0) {
    sections.push("## Agent Initialization Order");
    sections.push("");
    for (const agent of agents) {
      const phase = agent.phase != null ? agent.phase : 0;
      sections.push(
        `Phase ${phase}: ${agent.id} (${mapModel(agent.model ?? "sonnet")})`,
      );
    }
    sections.push("");
  }

  return {
    path: "BOOTSTRAP.md",
    content: sections.join("\n") + "\n",
  };
}

/** Generate TEAM.md — topology overview with mermaid flow diagram. */
function generateTeamMd(ast: TopologyAST): GeneratedFile {
  const agents = getAgentsSorted(ast);
  const gates = getGates(ast);
  const sections: string[] = [];

  sections.push(`# ${toTitle(ast.topology.name)} -- Topology Overview`);
  sections.push("");

  // Architecture summary
  sections.push("## Architecture");
  sections.push(`- Patterns: ${ast.topology.patterns.join(", ")}`);
  sections.push(`- Agents: ${agents.length}`);
  sections.push(`- Gates: ${gates.length}`);
  sections.push(`- Version: ${ast.topology.version}`);
  sections.push("");

  // Flow diagram
  if (ast.edges.length > 0) {
    sections.push("## Flow Diagram");
    sections.push("");
    sections.push("```mermaid");
    sections.push("graph TD");
    for (const edge of ast.edges) {
      let label = "";
      if (edge.condition) label += edge.condition;
      if (edge.maxIterations) {
        if (label) label += ", ";
        label += `max ${edge.maxIterations}`;
      }
      if (label) {
        sections.push(`  ${edge.from} -->|${label}| ${edge.to}`);
      } else {
        sections.push(`  ${edge.from} --> ${edge.to}`);
      }
    }
    sections.push("```");
    sections.push("");
  }

  // Roles table
  if (Object.keys(ast.roles).length > 0) {
    sections.push("## Roles");
    sections.push("| Role | Description |");
    sections.push("|------|-------------|");
    for (const [role, desc] of Object.entries(ast.roles)) {
      sections.push(`| ${role} | ${desc} |`);
    }
    sections.push("");
  }

  // Metering
  if (ast.metering) {
    sections.push("## Metering");
    sections.push(`- Track: ${ast.metering.track.join(", ")}`);
    sections.push(`- Per: ${ast.metering.per.join(", ")}`);
    sections.push(`- Output: ${ast.metering.output} (${ast.metering.format})`);
    sections.push(`- Pricing: ${ast.metering.pricing}`);
    sections.push("");
  }

  return {
    path: "TEAM.md",
    content: sections.join("\n") + "\n",
  };
}

/** Generate workspace-protocol.md — access rules from agent reads/writes. */
function generateWorkspaceProtocol(ast: TopologyAST): GeneratedFile | null {
  const agents = getAgentsSorted(ast);
  const agentsWithAccess = agents.filter(
    (a) =>
      (a.reads && a.reads.length > 0) || (a.writes && a.writes.length > 0),
  );
  if (agentsWithAccess.length === 0) return null;

  const sections: string[] = [];
  sections.push("# Workspace Protocol");
  sections.push("");

  // Directory structure from workspace
  const workspace = ast.memory.workspace as Record<string, unknown> | undefined;
  if (workspace?.structure && Array.isArray(workspace.structure)) {
    sections.push("## Directory Structure");
    for (const item of workspace.structure as string[]) {
      sections.push(`- ${item}/`);
    }
    sections.push("");
  }

  // Read/Write rules
  sections.push("## Access Rules");
  sections.push("");
  for (const agent of agentsWithAccess) {
    sections.push(`### ${toTitle(agent.id)}`);
    if (agent.reads && agent.reads.length > 0) {
      sections.push(`- **Reads:** ${agent.reads.join(", ")}`);
    }
    if (agent.writes && agent.writes.length > 0) {
      sections.push(`- **Writes:** ${agent.writes.join(", ")}`);
    }
    sections.push("");
  }

  return {
    path: "workspace-protocol.md",
    content: sections.join("\n") + "\n",
  };
}

/** Generate skill files from ast.skills. */
function generateSkillFiles(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  for (const skill of ast.skills) {
    const sections: string[] = [];
    sections.push(`# ${toTitle(skill.id)} Skill`);
    sections.push("");

    if (skill.description) {
      sections.push(skill.description);
      sections.push("");
    }
    if (skill.scripts && skill.scripts.length > 0) {
      sections.push("## Scripts");
      for (const s of skill.scripts) {
        sections.push(`- ${s}`);
      }
      sections.push("");
    }
    if (skill.domains && skill.domains.length > 0) {
      sections.push("## Domains");
      for (const d of skill.domains) {
        sections.push(`- ${d}`);
      }
      sections.push("");
    }
    if (skill.references && skill.references.length > 0) {
      sections.push("## References");
      for (const r of skill.references) {
        sections.push(`- ${r}`);
      }
      sections.push("");
    }

    files.push({
      path: `skills/${skill.id}/SKILL.md`,
      content: sections.join("\n") + "\n",
    });
  }

  return files;
}

/** Generate tool-as-skill wrappers from ast.toolDefs. */
function generateToolSkills(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  for (const tool of ast.toolDefs) {
    // SKILL.md wrapper
    const sections: string[] = [];
    sections.push(`# ${toTitle(tool.id)} Tool`);
    sections.push("");
    sections.push(tool.description);
    sections.push("");
    sections.push(`- Script: \`${tool.script}\``);
    if (tool.args && tool.args.length > 0) {
      sections.push(`- Args: ${tool.args.join(", ")}`);
    }
    if (tool.lang) {
      sections.push(`- Language: ${tool.lang}`);
    }
    sections.push("");

    files.push({
      path: `skills/${tool.id}/SKILL.md`,
      content: sections.join("\n") + "\n",
    });

    // index.ts stub
    const ext =
      tool.lang === "python" ? "py" : tool.lang === "node" ? "js" : "ts";
    const stubLines = [
      "// Auto-generated tool stub — edit as needed.",
      `// Tool: ${tool.id}`,
      `// ${tool.description}`,
      "",
    ];
    if (tool.args && tool.args.length > 0) {
      stubLines.push(`// Args: ${tool.args.join(", ")}`);
      stubLines.push("");
    }
    stubLines.push('console.log("TODO: implement tool");');
    stubLines.push("");

    files.push({
      path: `skills/${tool.id}/index.${ext}`,
      content: stubLines.join("\n"),
    });
  }

  return files;
}

/** Generate gate script stubs. */
function generateGateScripts(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const gates = getGates(ast);

  for (const gate of gates) {
    if (gate.run) {
      const scriptName = gate.run.replace(/^.*\//, "").replace(/\s.*$/, "");
      files.push({
        path: `scripts/${scriptName}`,
        content: shellStub(`Gate: ${gate.id} -- ${gate.run}`),
      });
    }
  }

  return files;
}

/** Generate hook script stubs. */
function generateHookScripts(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  for (const hook of ast.hooks) {
    if (!hook.run) continue;
    const scriptName = hook.run.replace(/^.*\//, "").replace(/\s.*$/, "");
    files.push({
      path: `scripts/${scriptName}`,
      content: [
        "#!/usr/bin/env bash",
        `# Hook: ${hook.name} -- fires on ${hook.on}`,
        "# Auto-generated by agentopology scaffold — edit as needed.",
        "set -euo pipefail",
        "",
        `echo "TODO: implement ${hook.name} hook"`,
        "",
      ].join("\n"),
    });
  }

  return files;
}

/** Generate memory directories (workspace structure + domains). */
function generateMemoryDirs(ast: TopologyAST): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // Workspace dirs
  const workspace = ast.memory.workspace as Record<string, unknown> | undefined;
  if (workspace) {
    files.push(gitkeep("workspace"));
    if (workspace.structure && Array.isArray(workspace.structure)) {
      for (const dir of workspace.structure as string[]) {
        files.push(gitkeep(`workspace/${dir}`));
      }
    }
  }

  // Domains dir
  files.push(gitkeep("domains"));

  return files;
}

/** Generate metering script + metrics file. */
function generateMetering(ast: TopologyAST): GeneratedFile[] {
  if (!ast.metering) return [];

  const m = ast.metering;
  const files: GeneratedFile[] = [];

  // collect-metrics.sh
  const lines = [
    "#!/usr/bin/env bash",
    "# Metering / cost tracking script",
    "# Auto-generated by agentopology scaffold — edit as needed.",
    "set -euo pipefail",
    "",
    `# Track: ${m.track.join(", ")}`,
    `# Per: ${m.per.join(", ")}`,
    `# Output: ${m.output} (${m.format})`,
    `# Pricing: ${m.pricing}`,
    "",
    'echo "TODO: implement metrics collection"',
    "",
  ];

  files.push({
    path: "scripts/collect-metrics.sh",
    content: lines.join("\n"),
  });

  // Empty metrics file
  files.push({
    path: "metrics.jsonl",
    content: "",
  });

  return files;
}

// ---------------------------------------------------------------------------
// Binding export
// ---------------------------------------------------------------------------

/** OpenClaw binding — multi-channel AI agent framework. */
export const openClawBinding: BindingTarget = {
  name: "openclaw",
  description:
    "OpenClaw workspace -- multi-channel AI agent framework with gateway, channels, and markdown-based agent identity",

  scaffold(ast: TopologyAST): GeneratedFile[] {
    const files: GeneratedFile[] = [];

    // 1. Core workspace files
    files.push(generateOpenClawJson(ast));
    files.push(generateSoulMd(ast));
    files.push(generateAgentsMd(ast));
    files.push(generateToolsMd(ast));
    files.push(generateMemoryMd(ast));
    files.push(generateBootstrapMd(ast));
    files.push(generateTeamMd(ast));

    // 2. Skills (from ast.skills + ast.toolDefs)
    files.push(...generateSkillFiles(ast));
    files.push(...generateToolSkills(ast));

    // 3. Scripts (gates + hooks + metering)
    files.push(...generateGateScripts(ast));
    files.push(...generateHookScripts(ast));
    files.push(...generateMetering(ast));

    // 4. Memory directories
    files.push(...generateMemoryDirs(ast));

    // 5. Workspace protocol
    const protocol = generateWorkspaceProtocol(ast);
    if (protocol) files.push(protocol);

    return files;
  },
};
