/**
 * Tests for Change 4 + 5: Agent-scoped env var injection + stub script generation.
 *
 * Change 4: When scaffold generates a hook stub, it must include logic to
 * extract ACTIVE_AGENT from the Claude Code stdin JSON payload (agent_type field).
 *
 * Change 5: When a hook's run: path does not exist on disk, scaffold emits a stub
 * at that path with:
 *   - #!/usr/bin/env bash shebang
 *   - jq-based AGENT_TYPE extraction from stdin
 *   - A metrics.jsonl append
 *   - chmod +x (executable bit)
 *   - Auto-generated marker comment
 */

import { describe, it, expect, beforeEach, afterEach } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";
import { parse } from "../../parser/index.js";
import { bindings } from "../index.js";
import type { GeneratedFile } from "../types.js";

let tmpDir: string;

beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "stub-gen-test-"));
});

afterEach(() => {
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

// ---------------------------------------------------------------------------
// Topology with a hook pointing at a non-existent script
// ---------------------------------------------------------------------------

const STUB_TOPOLOGY = `
topology stub-test : [supervisor] {
  meta { version: "1.0.0" description: "Stub generation test" }
  orchestrator { model: opus handles: [start] }
  action start { kind: inline }
  agent tracker { model: sonnet phase: 1 prompt { You are tracker. } }
  flow { start -> tracker }
  hooks {
    hook log-finish {
      on: SubagentStop
      matcher: "tracker"
      run: ".claude/scripts/log-finish.sh"
      type: command
      timeout: 5000
    }
  }
}
`;

// ---------------------------------------------------------------------------
// Change 5 — stub generation for non-existent hook scripts
// ---------------------------------------------------------------------------

describe("Change 5 — hook stub generation", () => {
  const ast = parse(STUB_TOPOLOGY);
  const binding = bindings["claude-code"];

  it("generates a stub script file for hook with non-existent run path", () => {
    const files: GeneratedFile[] = binding.scaffold(ast);
    // The stub should be at the path declared in hook.run
    const stub = files.find((f) => f.path === ".claude/scripts/log-finish.sh");
    expect(stub).toBeDefined();
  });

  it("stub file has category 'script'", () => {
    const files: GeneratedFile[] = binding.scaffold(ast);
    const stub = files.find((f) => f.path === ".claude/scripts/log-finish.sh");
    expect(stub!.category).toBe("script");
  });

  it("stub contains shebang line", () => {
    const files: GeneratedFile[] = binding.scaffold(ast);
    const stub = files.find((f) => f.path === ".claude/scripts/log-finish.sh");
    expect(stub!.content).toContain("#!/usr/bin/env bash");
  });

  it("stub contains auto-generated marker", () => {
    const files: GeneratedFile[] = binding.scaffold(ast);
    const stub = files.find((f) => f.path === ".claude/scripts/log-finish.sh");
    expect(stub!.content).toContain("Auto-generated by agentopology scaffold");
  });

  it("stub extracts AGENT_TYPE from stdin JSON (Change 4 — env var injection)", () => {
    const files: GeneratedFile[] = binding.scaffold(ast);
    const stub = files.find((f) => f.path === ".claude/scripts/log-finish.sh");
    // Stub must extract agent_type from the Claude Code stdin payload
    expect(stub!.content).toContain("agent_type");
    expect(stub!.content).toContain("AGENT_TYPE");
  });

  it("stub appends to metrics.jsonl", () => {
    const files: GeneratedFile[] = binding.scaffold(ast);
    const stub = files.find((f) => f.path === ".claude/scripts/log-finish.sh");
    expect(stub!.content).toContain("metrics.jsonl");
  });

  it("stub includes hook name in header comment", () => {
    const files: GeneratedFile[] = binding.scaffold(ast);
    const stub = files.find((f) => f.path === ".claude/scripts/log-finish.sh");
    expect(stub!.content).toContain("log-finish");
  });

  it("stub includes event name in header comment", () => {
    const files: GeneratedFile[] = binding.scaffold(ast);
    const stub = files.find((f) => f.path === ".claude/scripts/log-finish.sh");
    expect(stub!.content).toContain("SubagentStop");
  });

  it("stub is marked executable (via a generated chmod hint or content)", () => {
    // Since scaffold returns file content (not real fs writes), we check the
    // category is 'script' — the executeActions function sets chmod on creation.
    // The actual chmod happens in executeActions. We verify it in an integration
    // test by writing the file and checking the mode.
    const files: GeneratedFile[] = binding.scaffold(ast);
    const stub = files.find((f) => f.path === ".claude/scripts/log-finish.sh");
    expect(stub).toBeDefined();
    expect(stub!.category).toBe("script");
    expect(stub!.executable).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Change 5 — NO stub if the script already exists on disk (not scaffold's job)
// ---------------------------------------------------------------------------
// Note: scaffold() generates file lists; the incremental engine decides
// what to write. The stub is always in the generated list — the incremental
// engine's "script" category + shouldOverwriteScript() prevents overwriting
// user-edited stubs. This is correct behaviour, already tested in scaffold.test.ts.
