#!/usr/bin/env bash
# Action: db-verify — Execute DB verification queries between phases via Supabase MCP
# Auto-generated by agentopology scaffold — edit as needed.
set -euo pipefail


echo "TODO: implement inline action"
