#!/usr/bin/env bash
# Hook: bash-evidence-logger — fires on PostToolUse
# Auto-generated by agentopology scaffold — edit as needed.
set -euo pipefail

echo "TODO: implement bash-evidence-logger hook"
