/**
 * Tests for the cross-binding ownership guard.
 *
 * The regression these lock down: scaffolding a second binding into a project
 * that already has one used to silently replace the first binding's root
 * AGENTS.md, because a target with no manifest takes the unconditional
 * first-run write path.
 */

import { describe, it, expect, beforeEach, afterEach } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";
import { hashContent, writeManifest } from "../manifest.js";
import { describeOwner, findUnownedCollisions } from "../ownership.js";
import type { ScaffoldManifest } from "../types.js";
import type { GeneratedFile } from "../../bindings/types.js";

const TARGETS = ["claude-code", "codex", "cursor", "copilot-cli", "kiro", "openclaw"];

let tmpDir: string;

beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "ownership-test-"));
});

afterEach(() => {
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

/** Write a file relative to the temp project root, creating parent dirs. */
function writeAt(relPath: string, content: string): void {
  const abs = path.join(tmpDir, relPath);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, content, "utf-8");
}

/** Build a manifest claiming the given paths for a target. */
function manifestFor(target: string, files: string[]): ScaffoldManifest {
  const entries: ScaffoldManifest["files"] = {};
  for (const file of files) {
    entries[file] = { hash: hashContent(file), category: "machine" };
  }
  return {
    source: "test.at",
    sourceHash: hashContent("topology Test"),
    target,
    generatedAt: "2025-01-01T00:00:00.000Z",
    files: entries,
  };
}

const agentsMd = (content: string): GeneratedFile => ({
  path: "AGENTS.md",
  content,
  category: "agent",
});

describe("findUnownedCollisions", () => {
  it("reports nothing when no generated file exists on disk", () => {
    const collisions = findUnownedCollisions(
      tmpDir,
      "cursor",
      [agentsMd("# cursor\n")],
      TARGETS,
    );
    expect(collisions).toEqual([]);
  });

  it("ignores files whose on-disk content is byte-identical", () => {
    writeAt("AGENTS.md", "# same\n");

    const collisions = findUnownedCollisions(
      tmpDir,
      "cursor",
      [agentsMd("# same\n")],
      TARGETS,
    );
    expect(collisions).toEqual([]);
  });

  it("attributes a collision to the binding whose manifest claims the path", () => {
    writeAt("AGENTS.md", "# codex — the long one\n");
    writeManifest(tmpDir, "codex", manifestFor("codex", ["AGENTS.md"]));

    const collisions = findUnownedCollisions(
      tmpDir,
      "cursor",
      [agentsMd("# cursor summary table\n")],
      TARGETS,
    );

    expect(collisions).toEqual([{ path: "AGENTS.md", owner: "codex" }]);
  });

  it("reports an unclaimed collision with a null owner", () => {
    writeAt("AGENTS.md", "# hand-written by a human\n");

    const collisions = findUnownedCollisions(
      tmpDir,
      "cursor",
      [agentsMd("# cursor summary table\n")],
      TARGETS,
    );

    expect(collisions).toEqual([{ path: "AGENTS.md", owner: null }]);
  });

  it("does not attribute a path to the target being scaffolded", () => {
    writeAt("AGENTS.md", "# stale cursor output\n");
    writeManifest(tmpDir, "cursor", manifestFor("cursor", ["AGENTS.md"]));

    const collisions = findUnownedCollisions(
      tmpDir,
      "cursor",
      [agentsMd("# fresh cursor output\n")],
      TARGETS,
    );

    // Reached only via --force or a deleted manifest; either way the file is
    // not somebody else's, so no other binding may be named as its owner.
    expect(collisions).toEqual([{ path: "AGENTS.md", owner: null }]);
  });

  it("preserves generation order across several collisions", () => {
    writeAt("AGENTS.md", "# theirs\n");
    writeAt(".cursor/rules/planner.mdc", "user edited\n");
    writeManifest(tmpDir, "codex", manifestFor("codex", ["AGENTS.md"]));

    const collisions = findUnownedCollisions(
      tmpDir,
      "cursor",
      [
        agentsMd("# ours\n"),
        { path: ".cursor/rules/planner.mdc", content: "generated\n" },
      ],
      TARGETS,
    );

    expect(collisions.map((collision) => collision.path)).toEqual([
      "AGENTS.md",
      ".cursor/rules/planner.mdc",
    ]);
    expect(collisions[1].owner).toBeNull();
  });
});

describe("describeOwner", () => {
  it("names the owning scaffold when one is known", () => {
    expect(describeOwner({ path: "AGENTS.md", owner: "codex" })).toBe(
      'owned by the "codex" scaffold',
    );
  });

  it("falls back to a non-agentopology attribution", () => {
    expect(describeOwner({ path: "AGENTS.md", owner: null })).toBe(
      "not generated by agentopology",
    );
  });
});
