/**
 * Shared stub-script utilities for all bindings.
 *
 * A scaffold "stub" is a placeholder shell script generated when the topology
 * names a script (e.g. `gate.run: "scripts/lint.sh"`) but does not provide the
 * implementation. The user must fill it in before the topology runs for real.
 *
 * Stubs must be detectable by both humans and tools. We emit a unique marker
 * comment line — `# AGENTOPOLOGY_STUB ...` — that:
 *   - Won't appear in any user-written script unless they copied a stub.
 *   - Survives standard edits (the marker is a comment, not behavior).
 *   - Is grep-able from CI to detect un-implemented stubs.
 *
 * To detect a stub, use {@link isStubContent}. The marker is removed by the
 * user once they implement the script, which flips the file out of "stub"
 * state without any further action.
 *
 * @module
 */

/**
 * Machine-readable marker line emitted in every stub script. Detect with
 * {@link isStubContent} or grep for this exact string.
 *
 * Keep this stable — downstream tools (CI lint scripts, gate-runners, the
 * `agentopology stubs` command) match on it.
 */
export const STUB_MARKER = "# AGENTOPOLOGY_STUB — fill this in before relying on this script";

/**
 * Generate a shell script stub with a header comment and the {@link STUB_MARKER}.
 *
 * Output shape:
 *
 *   #!/usr/bin/env bash
 *   # <description>
 *   # Auto-generated by agentopology scaffold — edit as needed.
 *   # AGENTOPOLOGY_STUB — fill this in before relying on this script
 *   set -euo pipefail
 *
 *   echo "TODO: implement this script"
 *
 * The marker is the third comment line (after the description and the
 * auto-generated note) so it sits prominently at the top where a user is
 * likely to see it. Removing the marker line is the canonical way to flag the
 * script as "implemented" — `agentopology stubs` ignores files whose marker
 * has been stripped.
 */
export function shellStub(description: string): string {
  return [
    "#!/usr/bin/env bash",
    `# ${description}`,
    "# Auto-generated by agentopology scaffold — edit as needed.",
    STUB_MARKER,
    "set -euo pipefail",
    "",
    'echo "TODO: implement this script"',
    "",
  ].join("\n");
}

/**
 * Return true if the file content contains the {@link STUB_MARKER}, indicating
 * the script is an unimplemented scaffold stub.
 *
 * Use this from CI to detect topologies that haven't been finished, or from
 * the `agentopology stubs` command to list pending work.
 */
export function isStubContent(content: string): boolean {
  return content.includes(STUB_MARKER);
}
